package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Acknowledges generated by hbm2java
 */
public class Acknowledges implements java.io.Serializable {

	private long acknowledgeid;
	private Events events;
	private Users users;
	private int clock;
	private String message;

	public Acknowledges() {
	}

	public Acknowledges(long acknowledgeid, Events events, Users users,
			int clock, String message) {
		this.acknowledgeid = acknowledgeid;
		this.events = events;
		this.users = users;
		this.clock = clock;
		this.message = message;
	}

	public long getAcknowledgeid() {
		return this.acknowledgeid;
	}

	public void setAcknowledgeid(long acknowledgeid) {
		this.acknowledgeid = acknowledgeid;
	}

	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
