package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Actions generated by hbm2java
 */
public class Actions implements java.io.Serializable {

	private long actionid;
	private String name;
	private int eventsource;
	private int evaltype;
	private int status;
	private int escPeriod;
	private String defShortdata;
	private String defLongdata;
	private int recoveryMsg;
	private String RShortdata;
	private String RLongdata;
	private String formula;
	private Set alertses = new HashSet(0);
	private Set conditionses = new HashSet(0);
	private Set operationses = new HashSet(0);

	public Actions() {
	}

	public Actions(long actionid, String name, int eventsource, int evaltype,
			int status, int escPeriod, String defShortdata, String defLongdata,
			int recoveryMsg, String RShortdata, String RLongdata, String formula) {
		this.actionid = actionid;
		this.name = name;
		this.eventsource = eventsource;
		this.evaltype = evaltype;
		this.status = status;
		this.escPeriod = escPeriod;
		this.defShortdata = defShortdata;
		this.defLongdata = defLongdata;
		this.recoveryMsg = recoveryMsg;
		this.RShortdata = RShortdata;
		this.RLongdata = RLongdata;
		this.formula = formula;
	}

	public Actions(long actionid, String name, int eventsource, int evaltype,
			int status, int escPeriod, String defShortdata, String defLongdata,
			int recoveryMsg, String RShortdata, String RLongdata,
			String formula, Set alertses, Set conditionses, Set operationses) {
		this.actionid = actionid;
		this.name = name;
		this.eventsource = eventsource;
		this.evaltype = evaltype;
		this.status = status;
		this.escPeriod = escPeriod;
		this.defShortdata = defShortdata;
		this.defLongdata = defLongdata;
		this.recoveryMsg = recoveryMsg;
		this.RShortdata = RShortdata;
		this.RLongdata = RLongdata;
		this.formula = formula;
		this.alertses = alertses;
		this.conditionses = conditionses;
		this.operationses = operationses;
	}

	public long getActionid() {
		return this.actionid;
	}

	public void setActionid(long actionid) {
		this.actionid = actionid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getEventsource() {
		return this.eventsource;
	}

	public void setEventsource(int eventsource) {
		this.eventsource = eventsource;
	}

	public int getEvaltype() {
		return this.evaltype;
	}

	public void setEvaltype(int evaltype) {
		this.evaltype = evaltype;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getEscPeriod() {
		return this.escPeriod;
	}

	public void setEscPeriod(int escPeriod) {
		this.escPeriod = escPeriod;
	}

	public String getDefShortdata() {
		return this.defShortdata;
	}

	public void setDefShortdata(String defShortdata) {
		this.defShortdata = defShortdata;
	}

	public String getDefLongdata() {
		return this.defLongdata;
	}

	public void setDefLongdata(String defLongdata) {
		this.defLongdata = defLongdata;
	}

	public int getRecoveryMsg() {
		return this.recoveryMsg;
	}

	public void setRecoveryMsg(int recoveryMsg) {
		this.recoveryMsg = recoveryMsg;
	}

	public String getRShortdata() {
		return this.RShortdata;
	}

	public void setRShortdata(String RShortdata) {
		this.RShortdata = RShortdata;
	}

	public String getRLongdata() {
		return this.RLongdata;
	}

	public void setRLongdata(String RLongdata) {
		this.RLongdata = RLongdata;
	}

	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	public Set getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set alertses) {
		this.alertses = alertses;
	}

	public Set getConditionses() {
		return this.conditionses;
	}

	public void setConditionses(Set conditionses) {
		this.conditionses = conditionses;
	}

	public Set getOperationses() {
		return this.operationses;
	}

	public void setOperationses(Set operationses) {
		this.operationses = operationses;
	}

}
