package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Alerts generated by hbm2java
 */
public class Alerts implements java.io.Serializable {

	private long alertid;
	private Events events;
	private Actions actions;
	private MediaType mediaType;
	private Users users;
	private int clock;
	private String sendto;
	private String subject;
	private String message;
	private int status;
	private int retries;
	private String error;
	private int escStep;
	private int alerttype;

	public Alerts() {
	}

	public Alerts(long alertid, Events events, Actions actions, int clock,
			String sendto, String subject, String message, int status,
			int retries, String error, int escStep, int alerttype) {
		this.alertid = alertid;
		this.events = events;
		this.actions = actions;
		this.clock = clock;
		this.sendto = sendto;
		this.subject = subject;
		this.message = message;
		this.status = status;
		this.retries = retries;
		this.error = error;
		this.escStep = escStep;
		this.alerttype = alerttype;
	}

	public Alerts(long alertid, Events events, Actions actions,
			MediaType mediaType, Users users, int clock, String sendto,
			String subject, String message, int status, int retries,
			String error, int escStep, int alerttype) {
		this.alertid = alertid;
		this.events = events;
		this.actions = actions;
		this.mediaType = mediaType;
		this.users = users;
		this.clock = clock;
		this.sendto = sendto;
		this.subject = subject;
		this.message = message;
		this.status = status;
		this.retries = retries;
		this.error = error;
		this.escStep = escStep;
		this.alerttype = alerttype;
	}

	public long getAlertid() {
		return this.alertid;
	}

	public void setAlertid(long alertid) {
		this.alertid = alertid;
	}

	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	public MediaType getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(MediaType mediaType) {
		this.mediaType = mediaType;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public String getSendto() {
		return this.sendto;
	}

	public void setSendto(String sendto) {
		this.sendto = sendto;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getRetries() {
		return this.retries;
	}

	public void setRetries(int retries) {
		this.retries = retries;
	}

	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	public int getEscStep() {
		return this.escStep;
	}

	public void setEscStep(int escStep) {
		this.escStep = escStep;
	}

	public int getAlerttype() {
		return this.alerttype;
	}

	public void setAlerttype(int alerttype) {
		this.alerttype = alerttype;
	}

}
