package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ApplicationTemplate generated by hbm2java
 */
public class ApplicationTemplate implements java.io.Serializable {

	private long applicationTemplateid;
	private Applications applicationsByApplicationid;
	private Applications applicationsByTemplateid;

	public ApplicationTemplate() {
	}

	public ApplicationTemplate(long applicationTemplateid,
			Applications applicationsByApplicationid,
			Applications applicationsByTemplateid) {
		this.applicationTemplateid = applicationTemplateid;
		this.applicationsByApplicationid = applicationsByApplicationid;
		this.applicationsByTemplateid = applicationsByTemplateid;
	}

	public long getApplicationTemplateid() {
		return this.applicationTemplateid;
	}

	public void setApplicationTemplateid(long applicationTemplateid) {
		this.applicationTemplateid = applicationTemplateid;
	}

	public Applications getApplicationsByApplicationid() {
		return this.applicationsByApplicationid;
	}

	public void setApplicationsByApplicationid(
			Applications applicationsByApplicationid) {
		this.applicationsByApplicationid = applicationsByApplicationid;
	}

	public Applications getApplicationsByTemplateid() {
		return this.applicationsByTemplateid;
	}

	public void setApplicationsByTemplateid(
			Applications applicationsByTemplateid) {
		this.applicationsByTemplateid = applicationsByTemplateid;
	}

}
