package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationPrototype generated by hbm2java
 */
public class ApplicationPrototype implements java.io.Serializable {

	private long applicationPrototypeid;
	private Items items;
	private ApplicationPrototype applicationPrototype;
	private String name;
	private Set applicationPrototypes = new HashSet(0);
	private Set itemApplicationPrototypes = new HashSet(0);
	private Set applicationDiscoveries = new HashSet(0);

	public ApplicationPrototype() {
	}

	public ApplicationPrototype(long applicationPrototypeid, Items items,
			String name) {
		this.applicationPrototypeid = applicationPrototypeid;
		this.items = items;
		this.name = name;
	}

	public ApplicationPrototype(long applicationPrototypeid, Items items,
			ApplicationPrototype applicationPrototype, String name,
			Set applicationPrototypes, Set itemApplicationPrototypes,
			Set applicationDiscoveries) {
		this.applicationPrototypeid = applicationPrototypeid;
		this.items = items;
		this.applicationPrototype = applicationPrototype;
		this.name = name;
		this.applicationPrototypes = applicationPrototypes;
		this.itemApplicationPrototypes = itemApplicationPrototypes;
		this.applicationDiscoveries = applicationDiscoveries;
	}

	public long getApplicationPrototypeid() {
		return this.applicationPrototypeid;
	}

	public void setApplicationPrototypeid(long applicationPrototypeid) {
		this.applicationPrototypeid = applicationPrototypeid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public ApplicationPrototype getApplicationPrototype() {
		return this.applicationPrototype;
	}

	public void setApplicationPrototype(
			ApplicationPrototype applicationPrototype) {
		this.applicationPrototype = applicationPrototype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getApplicationPrototypes() {
		return this.applicationPrototypes;
	}

	public void setApplicationPrototypes(Set applicationPrototypes) {
		this.applicationPrototypes = applicationPrototypes;
	}

	public Set getItemApplicationPrototypes() {
		return this.itemApplicationPrototypes;
	}

	public void setItemApplicationPrototypes(Set itemApplicationPrototypes) {
		this.itemApplicationPrototypes = itemApplicationPrototypes;
	}

	public Set getApplicationDiscoveries() {
		return this.applicationDiscoveries;
	}

	public void setApplicationDiscoveries(Set applicationDiscoveries) {
		this.applicationDiscoveries = applicationDiscoveries;
	}

}
