package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ApplicationDiscovery generated by hbm2java
 */
public class ApplicationDiscovery implements java.io.Serializable {

	private long applicationDiscoveryid;
	private ApplicationPrototype applicationPrototype;
	private Applications applications;
	private String name;
	private int lastcheck;
	private int tsDelete;

	public ApplicationDiscovery() {
	}

	public ApplicationDiscovery(long applicationDiscoveryid,
			ApplicationPrototype applicationPrototype,
			Applications applications, String name, int lastcheck, int tsDelete) {
		this.applicationDiscoveryid = applicationDiscoveryid;
		this.applicationPrototype = applicationPrototype;
		this.applications = applications;
		this.name = name;
		this.lastcheck = lastcheck;
		this.tsDelete = tsDelete;
	}

	public long getApplicationDiscoveryid() {
		return this.applicationDiscoveryid;
	}

	public void setApplicationDiscoveryid(long applicationDiscoveryid) {
		this.applicationDiscoveryid = applicationDiscoveryid;
	}

	public ApplicationPrototype getApplicationPrototype() {
		return this.applicationPrototype;
	}

	public void setApplicationPrototype(
			ApplicationPrototype applicationPrototype) {
		this.applicationPrototype = applicationPrototype;
	}

	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getLastcheck() {
		return this.lastcheck;
	}

	public void setLastcheck(int lastcheck) {
		this.lastcheck = lastcheck;
	}

	public int getTsDelete() {
		return this.tsDelete;
	}

	public void setTsDelete(int tsDelete) {
		this.tsDelete = tsDelete;
	}

}
