package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * AuditlogDetails generated by hbm2java
 */
public class AuditlogDetails implements java.io.Serializable {

	private long auditdetailid;
	private Auditlog auditlog;
	private String tableName;
	private String fieldName;
	private String oldvalue;
	private String newvalue;

	public AuditlogDetails() {
	}

	public AuditlogDetails(long auditdetailid, Auditlog auditlog,
			String tableName, String fieldName, String oldvalue, String newvalue) {
		this.auditdetailid = auditdetailid;
		this.auditlog = auditlog;
		this.tableName = tableName;
		this.fieldName = fieldName;
		this.oldvalue = oldvalue;
		this.newvalue = newvalue;
	}

	public long getAuditdetailid() {
		return this.auditdetailid;
	}

	public void setAuditdetailid(long auditdetailid) {
		this.auditdetailid = auditdetailid;
	}

	public Auditlog getAuditlog() {
		return this.auditlog;
	}

	public void setAuditlog(Auditlog auditlog) {
		this.auditlog = auditlog;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getOldvalue() {
		return this.oldvalue;
	}

	public void setOldvalue(String oldvalue) {
		this.oldvalue = oldvalue;
	}

	public String getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(String newvalue) {
		this.newvalue = newvalue;
	}

}
