package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Auditlog generated by hbm2java
 */
public class Auditlog implements java.io.Serializable {

	private long auditid;
	private Users users;
	private int clock;
	private int action;
	private int resourcetype;
	private String details;
	private String ip;
	private long resourceid;
	private String resourcename;
	private Set auditlogDetailses = new HashSet(0);

	public Auditlog() {
	}

	public Auditlog(long auditid, Users users, int clock, int action,
			int resourcetype, String details, String ip, long resourceid,
			String resourcename) {
		this.auditid = auditid;
		this.users = users;
		this.clock = clock;
		this.action = action;
		this.resourcetype = resourcetype;
		this.details = details;
		this.ip = ip;
		this.resourceid = resourceid;
		this.resourcename = resourcename;
	}

	public Auditlog(long auditid, Users users, int clock, int action,
			int resourcetype, String details, String ip, long resourceid,
			String resourcename, Set auditlogDetailses) {
		this.auditid = auditid;
		this.users = users;
		this.clock = clock;
		this.action = action;
		this.resourcetype = resourcetype;
		this.details = details;
		this.ip = ip;
		this.resourceid = resourceid;
		this.resourcename = resourcename;
		this.auditlogDetailses = auditlogDetailses;
	}

	public long getAuditid() {
		return this.auditid;
	}

	public void setAuditid(long auditid) {
		this.auditid = auditid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public int getAction() {
		return this.action;
	}

	public void setAction(int action) {
		this.action = action;
	}

	public int getResourcetype() {
		return this.resourcetype;
	}

	public void setResourcetype(int resourcetype) {
		this.resourcetype = resourcetype;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public long getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(long resourceid) {
		this.resourceid = resourceid;
	}

	public String getResourcename() {
		return this.resourcename;
	}

	public void setResourcename(String resourcename) {
		this.resourcename = resourcename;
	}

	public Set getAuditlogDetailses() {
		return this.auditlogDetailses;
	}

	public void setAuditlogDetailses(Set auditlogDetailses) {
		this.auditlogDetailses = auditlogDetailses;
	}

}
