package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * AutoregHost generated by hbm2java
 */
public class AutoregHost implements java.io.Serializable {

	private long autoregHostid;
	private Hosts hosts;
	private String host;
	private String listenIp;
	private int listenPort;
	private String listenDns;
	private String hostMetadata;

	public AutoregHost() {
	}

	public AutoregHost(long autoregHostid, String host, String listenIp,
			int listenPort, String listenDns, String hostMetadata) {
		this.autoregHostid = autoregHostid;
		this.host = host;
		this.listenIp = listenIp;
		this.listenPort = listenPort;
		this.listenDns = listenDns;
		this.hostMetadata = hostMetadata;
	}

	public AutoregHost(long autoregHostid, Hosts hosts, String host,
			String listenIp, int listenPort, String listenDns,
			String hostMetadata) {
		this.autoregHostid = autoregHostid;
		this.hosts = hosts;
		this.host = host;
		this.listenIp = listenIp;
		this.listenPort = listenPort;
		this.listenDns = listenDns;
		this.hostMetadata = hostMetadata;
	}

	public long getAutoregHostid() {
		return this.autoregHostid;
	}

	public void setAutoregHostid(long autoregHostid) {
		this.autoregHostid = autoregHostid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getListenIp() {
		return this.listenIp;
	}

	public void setListenIp(String listenIp) {
		this.listenIp = listenIp;
	}

	public int getListenPort() {
		return this.listenPort;
	}

	public void setListenPort(int listenPort) {
		this.listenPort = listenPort;
	}

	public String getListenDns() {
		return this.listenDns;
	}

	public void setListenDns(String listenDns) {
		this.listenDns = listenDns;
	}

	public String getHostMetadata() {
		return this.hostMetadata;
	}

	public void setHostMetadata(String hostMetadata) {
		this.hostMetadata = hostMetadata;
	}

}
