package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Conditions generated by hbm2java
 */
public class Conditions implements java.io.Serializable {

	private long conditionid;
	private Actions actions;
	private int conditiontype;
	private int operator;
	private String value;

	public Conditions() {
	}

	public Conditions(long conditionid, Actions actions, int conditiontype,
			int operator, String value) {
		this.conditionid = conditionid;
		this.actions = actions;
		this.conditiontype = conditiontype;
		this.operator = operator;
		this.value = value;
	}

	public long getConditionid() {
		return this.conditionid;
	}

	public void setConditionid(long conditionid) {
		this.conditionid = conditionid;
	}

	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	public int getConditiontype() {
		return this.conditiontype;
	}

	public void setConditiontype(int conditiontype) {
		this.conditiontype = conditiontype;
	}

	public int getOperator() {
		return this.operator;
	}

	public void setOperator(int operator) {
		this.operator = operator;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
