package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Config generated by hbm2java
 */
public class Config implements java.io.Serializable {

	private long configid;
	private Usrgrp usrgrp;
	private Groups groups;
	private int refreshUnsupported;
	private String workPeriod;
	private int eventAckEnable;
	private int eventExpire;
	private int eventShowMax;
	private String defaultTheme;
	private int authenticationType;
	private String ldapHost;
	private int ldapPort;
	private String ldapBaseDn;
	private String ldapBindDn;
	private String ldapBindPassword;
	private String ldapSearchAttribute;
	private int dropdownFirstEntry;
	private int dropdownFirstRemember;
	private int maxInTable;
	private int searchLimit;
	private String severityColor0;
	private String severityColor1;
	private String severityColor2;
	private String severityColor3;
	private String severityColor4;
	private String severityColor5;
	private String severityName0;
	private String severityName1;
	private String severityName2;
	private String severityName3;
	private String severityName4;
	private String severityName5;
	private int okPeriod;
	private int blinkPeriod;
	private String problemUnackColor;
	private String problemAckColor;
	private String okUnackColor;
	private String okAckColor;
	private int problemUnackStyle;
	private int problemAckStyle;
	private int okUnackStyle;
	private int okAckStyle;
	private int snmptrapLogging;
	private int serverCheckInterval;
	private int hkEventsMode;
	private int hkEventsTrigger;
	private int hkEventsInternal;
	private int hkEventsDiscovery;
	private int hkEventsAutoreg;
	private int hkServicesMode;
	private int hkServices;
	private int hkAuditMode;
	private int hkAudit;
	private int hkSessionsMode;
	private int hkSessions;
	private int hkHistoryMode;
	private int hkHistoryGlobal;
	private int hkHistory;
	private int hkTrendsMode;
	private int hkTrendsGlobal;
	private int hkTrends;
	private int defaultInventoryMode;

	public Config() {
	}

	public Config(long configid, Groups groups, int refreshUnsupported,
			String workPeriod, int eventAckEnable, int eventExpire,
			int eventShowMax, String defaultTheme, int authenticationType,
			String ldapHost, int ldapPort, String ldapBaseDn,
			String ldapBindDn, String ldapBindPassword,
			String ldapSearchAttribute, int dropdownFirstEntry,
			int dropdownFirstRemember, int maxInTable, int searchLimit,
			String severityColor0, String severityColor1,
			String severityColor2, String severityColor3,
			String severityColor4, String severityColor5, String severityName0,
			String severityName1, String severityName2, String severityName3,
			String severityName4, String severityName5, int okPeriod,
			int blinkPeriod, String problemUnackColor, String problemAckColor,
			String okUnackColor, String okAckColor, int problemUnackStyle,
			int problemAckStyle, int okUnackStyle, int okAckStyle,
			int snmptrapLogging, int serverCheckInterval, int hkEventsMode,
			int hkEventsTrigger, int hkEventsInternal, int hkEventsDiscovery,
			int hkEventsAutoreg, int hkServicesMode, int hkServices,
			int hkAuditMode, int hkAudit, int hkSessionsMode, int hkSessions,
			int hkHistoryMode, int hkHistoryGlobal, int hkHistory,
			int hkTrendsMode, int hkTrendsGlobal, int hkTrends,
			int defaultInventoryMode) {
		this.configid = configid;
		this.groups = groups;
		this.refreshUnsupported = refreshUnsupported;
		this.workPeriod = workPeriod;
		this.eventAckEnable = eventAckEnable;
		this.eventExpire = eventExpire;
		this.eventShowMax = eventShowMax;
		this.defaultTheme = defaultTheme;
		this.authenticationType = authenticationType;
		this.ldapHost = ldapHost;
		this.ldapPort = ldapPort;
		this.ldapBaseDn = ldapBaseDn;
		this.ldapBindDn = ldapBindDn;
		this.ldapBindPassword = ldapBindPassword;
		this.ldapSearchAttribute = ldapSearchAttribute;
		this.dropdownFirstEntry = dropdownFirstEntry;
		this.dropdownFirstRemember = dropdownFirstRemember;
		this.maxInTable = maxInTable;
		this.searchLimit = searchLimit;
		this.severityColor0 = severityColor0;
		this.severityColor1 = severityColor1;
		this.severityColor2 = severityColor2;
		this.severityColor3 = severityColor3;
		this.severityColor4 = severityColor4;
		this.severityColor5 = severityColor5;
		this.severityName0 = severityName0;
		this.severityName1 = severityName1;
		this.severityName2 = severityName2;
		this.severityName3 = severityName3;
		this.severityName4 = severityName4;
		this.severityName5 = severityName5;
		this.okPeriod = okPeriod;
		this.blinkPeriod = blinkPeriod;
		this.problemUnackColor = problemUnackColor;
		this.problemAckColor = problemAckColor;
		this.okUnackColor = okUnackColor;
		this.okAckColor = okAckColor;
		this.problemUnackStyle = problemUnackStyle;
		this.problemAckStyle = problemAckStyle;
		this.okUnackStyle = okUnackStyle;
		this.okAckStyle = okAckStyle;
		this.snmptrapLogging = snmptrapLogging;
		this.serverCheckInterval = serverCheckInterval;
		this.hkEventsMode = hkEventsMode;
		this.hkEventsTrigger = hkEventsTrigger;
		this.hkEventsInternal = hkEventsInternal;
		this.hkEventsDiscovery = hkEventsDiscovery;
		this.hkEventsAutoreg = hkEventsAutoreg;
		this.hkServicesMode = hkServicesMode;
		this.hkServices = hkServices;
		this.hkAuditMode = hkAuditMode;
		this.hkAudit = hkAudit;
		this.hkSessionsMode = hkSessionsMode;
		this.hkSessions = hkSessions;
		this.hkHistoryMode = hkHistoryMode;
		this.hkHistoryGlobal = hkHistoryGlobal;
		this.hkHistory = hkHistory;
		this.hkTrendsMode = hkTrendsMode;
		this.hkTrendsGlobal = hkTrendsGlobal;
		this.hkTrends = hkTrends;
		this.defaultInventoryMode = defaultInventoryMode;
	}

	public Config(long configid, Usrgrp usrgrp, Groups groups,
			int refreshUnsupported, String workPeriod, int eventAckEnable,
			int eventExpire, int eventShowMax, String defaultTheme,
			int authenticationType, String ldapHost, int ldapPort,
			String ldapBaseDn, String ldapBindDn, String ldapBindPassword,
			String ldapSearchAttribute, int dropdownFirstEntry,
			int dropdownFirstRemember, int maxInTable, int searchLimit,
			String severityColor0, String severityColor1,
			String severityColor2, String severityColor3,
			String severityColor4, String severityColor5, String severityName0,
			String severityName1, String severityName2, String severityName3,
			String severityName4, String severityName5, int okPeriod,
			int blinkPeriod, String problemUnackColor, String problemAckColor,
			String okUnackColor, String okAckColor, int problemUnackStyle,
			int problemAckStyle, int okUnackStyle, int okAckStyle,
			int snmptrapLogging, int serverCheckInterval, int hkEventsMode,
			int hkEventsTrigger, int hkEventsInternal, int hkEventsDiscovery,
			int hkEventsAutoreg, int hkServicesMode, int hkServices,
			int hkAuditMode, int hkAudit, int hkSessionsMode, int hkSessions,
			int hkHistoryMode, int hkHistoryGlobal, int hkHistory,
			int hkTrendsMode, int hkTrendsGlobal, int hkTrends,
			int defaultInventoryMode) {
		this.configid = configid;
		this.usrgrp = usrgrp;
		this.groups = groups;
		this.refreshUnsupported = refreshUnsupported;
		this.workPeriod = workPeriod;
		this.eventAckEnable = eventAckEnable;
		this.eventExpire = eventExpire;
		this.eventShowMax = eventShowMax;
		this.defaultTheme = defaultTheme;
		this.authenticationType = authenticationType;
		this.ldapHost = ldapHost;
		this.ldapPort = ldapPort;
		this.ldapBaseDn = ldapBaseDn;
		this.ldapBindDn = ldapBindDn;
		this.ldapBindPassword = ldapBindPassword;
		this.ldapSearchAttribute = ldapSearchAttribute;
		this.dropdownFirstEntry = dropdownFirstEntry;
		this.dropdownFirstRemember = dropdownFirstRemember;
		this.maxInTable = maxInTable;
		this.searchLimit = searchLimit;
		this.severityColor0 = severityColor0;
		this.severityColor1 = severityColor1;
		this.severityColor2 = severityColor2;
		this.severityColor3 = severityColor3;
		this.severityColor4 = severityColor4;
		this.severityColor5 = severityColor5;
		this.severityName0 = severityName0;
		this.severityName1 = severityName1;
		this.severityName2 = severityName2;
		this.severityName3 = severityName3;
		this.severityName4 = severityName4;
		this.severityName5 = severityName5;
		this.okPeriod = okPeriod;
		this.blinkPeriod = blinkPeriod;
		this.problemUnackColor = problemUnackColor;
		this.problemAckColor = problemAckColor;
		this.okUnackColor = okUnackColor;
		this.okAckColor = okAckColor;
		this.problemUnackStyle = problemUnackStyle;
		this.problemAckStyle = problemAckStyle;
		this.okUnackStyle = okUnackStyle;
		this.okAckStyle = okAckStyle;
		this.snmptrapLogging = snmptrapLogging;
		this.serverCheckInterval = serverCheckInterval;
		this.hkEventsMode = hkEventsMode;
		this.hkEventsTrigger = hkEventsTrigger;
		this.hkEventsInternal = hkEventsInternal;
		this.hkEventsDiscovery = hkEventsDiscovery;
		this.hkEventsAutoreg = hkEventsAutoreg;
		this.hkServicesMode = hkServicesMode;
		this.hkServices = hkServices;
		this.hkAuditMode = hkAuditMode;
		this.hkAudit = hkAudit;
		this.hkSessionsMode = hkSessionsMode;
		this.hkSessions = hkSessions;
		this.hkHistoryMode = hkHistoryMode;
		this.hkHistoryGlobal = hkHistoryGlobal;
		this.hkHistory = hkHistory;
		this.hkTrendsMode = hkTrendsMode;
		this.hkTrendsGlobal = hkTrendsGlobal;
		this.hkTrends = hkTrends;
		this.defaultInventoryMode = defaultInventoryMode;
	}

	public long getConfigid() {
		return this.configid;
	}

	public void setConfigid(long configid) {
		this.configid = configid;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public int getRefreshUnsupported() {
		return this.refreshUnsupported;
	}

	public void setRefreshUnsupported(int refreshUnsupported) {
		this.refreshUnsupported = refreshUnsupported;
	}

	public String getWorkPeriod() {
		return this.workPeriod;
	}

	public void setWorkPeriod(String workPeriod) {
		this.workPeriod = workPeriod;
	}

	public int getEventAckEnable() {
		return this.eventAckEnable;
	}

	public void setEventAckEnable(int eventAckEnable) {
		this.eventAckEnable = eventAckEnable;
	}

	public int getEventExpire() {
		return this.eventExpire;
	}

	public void setEventExpire(int eventExpire) {
		this.eventExpire = eventExpire;
	}

	public int getEventShowMax() {
		return this.eventShowMax;
	}

	public void setEventShowMax(int eventShowMax) {
		this.eventShowMax = eventShowMax;
	}

	public String getDefaultTheme() {
		return this.defaultTheme;
	}

	public void setDefaultTheme(String defaultTheme) {
		this.defaultTheme = defaultTheme;
	}

	public int getAuthenticationType() {
		return this.authenticationType;
	}

	public void setAuthenticationType(int authenticationType) {
		this.authenticationType = authenticationType;
	}

	public String getLdapHost() {
		return this.ldapHost;
	}

	public void setLdapHost(String ldapHost) {
		this.ldapHost = ldapHost;
	}

	public int getLdapPort() {
		return this.ldapPort;
	}

	public void setLdapPort(int ldapPort) {
		this.ldapPort = ldapPort;
	}

	public String getLdapBaseDn() {
		return this.ldapBaseDn;
	}

	public void setLdapBaseDn(String ldapBaseDn) {
		this.ldapBaseDn = ldapBaseDn;
	}

	public String getLdapBindDn() {
		return this.ldapBindDn;
	}

	public void setLdapBindDn(String ldapBindDn) {
		this.ldapBindDn = ldapBindDn;
	}

	public String getLdapBindPassword() {
		return this.ldapBindPassword;
	}

	public void setLdapBindPassword(String ldapBindPassword) {
		this.ldapBindPassword = ldapBindPassword;
	}

	public String getLdapSearchAttribute() {
		return this.ldapSearchAttribute;
	}

	public void setLdapSearchAttribute(String ldapSearchAttribute) {
		this.ldapSearchAttribute = ldapSearchAttribute;
	}

	public int getDropdownFirstEntry() {
		return this.dropdownFirstEntry;
	}

	public void setDropdownFirstEntry(int dropdownFirstEntry) {
		this.dropdownFirstEntry = dropdownFirstEntry;
	}

	public int getDropdownFirstRemember() {
		return this.dropdownFirstRemember;
	}

	public void setDropdownFirstRemember(int dropdownFirstRemember) {
		this.dropdownFirstRemember = dropdownFirstRemember;
	}

	public int getMaxInTable() {
		return this.maxInTable;
	}

	public void setMaxInTable(int maxInTable) {
		this.maxInTable = maxInTable;
	}

	public int getSearchLimit() {
		return this.searchLimit;
	}

	public void setSearchLimit(int searchLimit) {
		this.searchLimit = searchLimit;
	}

	public String getSeverityColor0() {
		return this.severityColor0;
	}

	public void setSeverityColor0(String severityColor0) {
		this.severityColor0 = severityColor0;
	}

	public String getSeverityColor1() {
		return this.severityColor1;
	}

	public void setSeverityColor1(String severityColor1) {
		this.severityColor1 = severityColor1;
	}

	public String getSeverityColor2() {
		return this.severityColor2;
	}

	public void setSeverityColor2(String severityColor2) {
		this.severityColor2 = severityColor2;
	}

	public String getSeverityColor3() {
		return this.severityColor3;
	}

	public void setSeverityColor3(String severityColor3) {
		this.severityColor3 = severityColor3;
	}

	public String getSeverityColor4() {
		return this.severityColor4;
	}

	public void setSeverityColor4(String severityColor4) {
		this.severityColor4 = severityColor4;
	}

	public String getSeverityColor5() {
		return this.severityColor5;
	}

	public void setSeverityColor5(String severityColor5) {
		this.severityColor5 = severityColor5;
	}

	public String getSeverityName0() {
		return this.severityName0;
	}

	public void setSeverityName0(String severityName0) {
		this.severityName0 = severityName0;
	}

	public String getSeverityName1() {
		return this.severityName1;
	}

	public void setSeverityName1(String severityName1) {
		this.severityName1 = severityName1;
	}

	public String getSeverityName2() {
		return this.severityName2;
	}

	public void setSeverityName2(String severityName2) {
		this.severityName2 = severityName2;
	}

	public String getSeverityName3() {
		return this.severityName3;
	}

	public void setSeverityName3(String severityName3) {
		this.severityName3 = severityName3;
	}

	public String getSeverityName4() {
		return this.severityName4;
	}

	public void setSeverityName4(String severityName4) {
		this.severityName4 = severityName4;
	}

	public String getSeverityName5() {
		return this.severityName5;
	}

	public void setSeverityName5(String severityName5) {
		this.severityName5 = severityName5;
	}

	public int getOkPeriod() {
		return this.okPeriod;
	}

	public void setOkPeriod(int okPeriod) {
		this.okPeriod = okPeriod;
	}

	public int getBlinkPeriod() {
		return this.blinkPeriod;
	}

	public void setBlinkPeriod(int blinkPeriod) {
		this.blinkPeriod = blinkPeriod;
	}

	public String getProblemUnackColor() {
		return this.problemUnackColor;
	}

	public void setProblemUnackColor(String problemUnackColor) {
		this.problemUnackColor = problemUnackColor;
	}

	public String getProblemAckColor() {
		return this.problemAckColor;
	}

	public void setProblemAckColor(String problemAckColor) {
		this.problemAckColor = problemAckColor;
	}

	public String getOkUnackColor() {
		return this.okUnackColor;
	}

	public void setOkUnackColor(String okUnackColor) {
		this.okUnackColor = okUnackColor;
	}

	public String getOkAckColor() {
		return this.okAckColor;
	}

	public void setOkAckColor(String okAckColor) {
		this.okAckColor = okAckColor;
	}

	public int getProblemUnackStyle() {
		return this.problemUnackStyle;
	}

	public void setProblemUnackStyle(int problemUnackStyle) {
		this.problemUnackStyle = problemUnackStyle;
	}

	public int getProblemAckStyle() {
		return this.problemAckStyle;
	}

	public void setProblemAckStyle(int problemAckStyle) {
		this.problemAckStyle = problemAckStyle;
	}

	public int getOkUnackStyle() {
		return this.okUnackStyle;
	}

	public void setOkUnackStyle(int okUnackStyle) {
		this.okUnackStyle = okUnackStyle;
	}

	public int getOkAckStyle() {
		return this.okAckStyle;
	}

	public void setOkAckStyle(int okAckStyle) {
		this.okAckStyle = okAckStyle;
	}

	public int getSnmptrapLogging() {
		return this.snmptrapLogging;
	}

	public void setSnmptrapLogging(int snmptrapLogging) {
		this.snmptrapLogging = snmptrapLogging;
	}

	public int getServerCheckInterval() {
		return this.serverCheckInterval;
	}

	public void setServerCheckInterval(int serverCheckInterval) {
		this.serverCheckInterval = serverCheckInterval;
	}

	public int getHkEventsMode() {
		return this.hkEventsMode;
	}

	public void setHkEventsMode(int hkEventsMode) {
		this.hkEventsMode = hkEventsMode;
	}

	public int getHkEventsTrigger() {
		return this.hkEventsTrigger;
	}

	public void setHkEventsTrigger(int hkEventsTrigger) {
		this.hkEventsTrigger = hkEventsTrigger;
	}

	public int getHkEventsInternal() {
		return this.hkEventsInternal;
	}

	public void setHkEventsInternal(int hkEventsInternal) {
		this.hkEventsInternal = hkEventsInternal;
	}

	public int getHkEventsDiscovery() {
		return this.hkEventsDiscovery;
	}

	public void setHkEventsDiscovery(int hkEventsDiscovery) {
		this.hkEventsDiscovery = hkEventsDiscovery;
	}

	public int getHkEventsAutoreg() {
		return this.hkEventsAutoreg;
	}

	public void setHkEventsAutoreg(int hkEventsAutoreg) {
		this.hkEventsAutoreg = hkEventsAutoreg;
	}

	public int getHkServicesMode() {
		return this.hkServicesMode;
	}

	public void setHkServicesMode(int hkServicesMode) {
		this.hkServicesMode = hkServicesMode;
	}

	public int getHkServices() {
		return this.hkServices;
	}

	public void setHkServices(int hkServices) {
		this.hkServices = hkServices;
	}

	public int getHkAuditMode() {
		return this.hkAuditMode;
	}

	public void setHkAuditMode(int hkAuditMode) {
		this.hkAuditMode = hkAuditMode;
	}

	public int getHkAudit() {
		return this.hkAudit;
	}

	public void setHkAudit(int hkAudit) {
		this.hkAudit = hkAudit;
	}

	public int getHkSessionsMode() {
		return this.hkSessionsMode;
	}

	public void setHkSessionsMode(int hkSessionsMode) {
		this.hkSessionsMode = hkSessionsMode;
	}

	public int getHkSessions() {
		return this.hkSessions;
	}

	public void setHkSessions(int hkSessions) {
		this.hkSessions = hkSessions;
	}

	public int getHkHistoryMode() {
		return this.hkHistoryMode;
	}

	public void setHkHistoryMode(int hkHistoryMode) {
		this.hkHistoryMode = hkHistoryMode;
	}

	public int getHkHistoryGlobal() {
		return this.hkHistoryGlobal;
	}

	public void setHkHistoryGlobal(int hkHistoryGlobal) {
		this.hkHistoryGlobal = hkHistoryGlobal;
	}

	public int getHkHistory() {
		return this.hkHistory;
	}

	public void setHkHistory(int hkHistory) {
		this.hkHistory = hkHistory;
	}

	public int getHkTrendsMode() {
		return this.hkTrendsMode;
	}

	public void setHkTrendsMode(int hkTrendsMode) {
		this.hkTrendsMode = hkTrendsMode;
	}

	public int getHkTrendsGlobal() {
		return this.hkTrendsGlobal;
	}

	public void setHkTrendsGlobal(int hkTrendsGlobal) {
		this.hkTrendsGlobal = hkTrendsGlobal;
	}

	public int getHkTrends() {
		return this.hkTrends;
	}

	public void setHkTrends(int hkTrends) {
		this.hkTrends = hkTrends;
	}

	public int getDefaultInventoryMode() {
		return this.defaultInventoryMode;
	}

	public void setDefaultInventoryMode(int defaultInventoryMode) {
		this.defaultInventoryMode = defaultInventoryMode;
	}

}
