package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Dbversion generated by hbm2java
 */
public class Dbversion implements java.io.Serializable {

	private DbversionId id;

	public Dbversion() {
	}

	public Dbversion(DbversionId id) {
		this.id = id;
	}

	public DbversionId getId() {
		return this.id;
	}

	public void setId(DbversionId id) {
		this.id = id;
	}

}
