package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Dchecks generated by hbm2java
 */
public class Dchecks implements java.io.Serializable {

	private long dcheckid;
	private Drules drules;
	private int type;
	private String key;
	private String snmpCommunity;
	private String ports;
	private String snmpv3Securityname;
	private int snmpv3Securitylevel;
	private String snmpv3Authpassphrase;
	private String snmpv3Privpassphrase;
	private int uniq;
	private int snmpv3Authprotocol;
	private int snmpv3Privprotocol;
	private String snmpv3Contextname;
	private Set dserviceses = new HashSet(0);

	public Dchecks() {
	}

	public Dchecks(long dcheckid, Drules drules, int type, String key,
			String snmpCommunity, String ports, String snmpv3Securityname,
			int snmpv3Securitylevel, String snmpv3Authpassphrase,
			String snmpv3Privpassphrase, int uniq, int snmpv3Authprotocol,
			int snmpv3Privprotocol, String snmpv3Contextname) {
		this.dcheckid = dcheckid;
		this.drules = drules;
		this.type = type;
		this.key = key;
		this.snmpCommunity = snmpCommunity;
		this.ports = ports;
		this.snmpv3Securityname = snmpv3Securityname;
		this.snmpv3Securitylevel = snmpv3Securitylevel;
		this.snmpv3Authpassphrase = snmpv3Authpassphrase;
		this.snmpv3Privpassphrase = snmpv3Privpassphrase;
		this.uniq = uniq;
		this.snmpv3Authprotocol = snmpv3Authprotocol;
		this.snmpv3Privprotocol = snmpv3Privprotocol;
		this.snmpv3Contextname = snmpv3Contextname;
	}

	public Dchecks(long dcheckid, Drules drules, int type, String key,
			String snmpCommunity, String ports, String snmpv3Securityname,
			int snmpv3Securitylevel, String snmpv3Authpassphrase,
			String snmpv3Privpassphrase, int uniq, int snmpv3Authprotocol,
			int snmpv3Privprotocol, String snmpv3Contextname, Set dserviceses) {
		this.dcheckid = dcheckid;
		this.drules = drules;
		this.type = type;
		this.key = key;
		this.snmpCommunity = snmpCommunity;
		this.ports = ports;
		this.snmpv3Securityname = snmpv3Securityname;
		this.snmpv3Securitylevel = snmpv3Securitylevel;
		this.snmpv3Authpassphrase = snmpv3Authpassphrase;
		this.snmpv3Privpassphrase = snmpv3Privpassphrase;
		this.uniq = uniq;
		this.snmpv3Authprotocol = snmpv3Authprotocol;
		this.snmpv3Privprotocol = snmpv3Privprotocol;
		this.snmpv3Contextname = snmpv3Contextname;
		this.dserviceses = dserviceses;
	}

	public long getDcheckid() {
		return this.dcheckid;
	}

	public void setDcheckid(long dcheckid) {
		this.dcheckid = dcheckid;
	}

	public Drules getDrules() {
		return this.drules;
	}

	public void setDrules(Drules drules) {
		this.drules = drules;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getSnmpCommunity() {
		return this.snmpCommunity;
	}

	public void setSnmpCommunity(String snmpCommunity) {
		this.snmpCommunity = snmpCommunity;
	}

	public String getPorts() {
		return this.ports;
	}

	public void setPorts(String ports) {
		this.ports = ports;
	}

	public String getSnmpv3Securityname() {
		return this.snmpv3Securityname;
	}

	public void setSnmpv3Securityname(String snmpv3Securityname) {
		this.snmpv3Securityname = snmpv3Securityname;
	}

	public int getSnmpv3Securitylevel() {
		return this.snmpv3Securitylevel;
	}

	public void setSnmpv3Securitylevel(int snmpv3Securitylevel) {
		this.snmpv3Securitylevel = snmpv3Securitylevel;
	}

	public String getSnmpv3Authpassphrase() {
		return this.snmpv3Authpassphrase;
	}

	public void setSnmpv3Authpassphrase(String snmpv3Authpassphrase) {
		this.snmpv3Authpassphrase = snmpv3Authpassphrase;
	}

	public String getSnmpv3Privpassphrase() {
		return this.snmpv3Privpassphrase;
	}

	public void setSnmpv3Privpassphrase(String snmpv3Privpassphrase) {
		this.snmpv3Privpassphrase = snmpv3Privpassphrase;
	}

	public int getUniq() {
		return this.uniq;
	}

	public void setUniq(int uniq) {
		this.uniq = uniq;
	}

	public int getSnmpv3Authprotocol() {
		return this.snmpv3Authprotocol;
	}

	public void setSnmpv3Authprotocol(int snmpv3Authprotocol) {
		this.snmpv3Authprotocol = snmpv3Authprotocol;
	}

	public int getSnmpv3Privprotocol() {
		return this.snmpv3Privprotocol;
	}

	public void setSnmpv3Privprotocol(int snmpv3Privprotocol) {
		this.snmpv3Privprotocol = snmpv3Privprotocol;
	}

	public String getSnmpv3Contextname() {
		return this.snmpv3Contextname;
	}

	public void setSnmpv3Contextname(String snmpv3Contextname) {
		this.snmpv3Contextname = snmpv3Contextname;
	}

	public Set getDserviceses() {
		return this.dserviceses;
	}

	public void setDserviceses(Set dserviceses) {
		this.dserviceses = dserviceses;
	}

}
