package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Dhosts generated by hbm2java
 */
public class Dhosts implements java.io.Serializable {

	private long dhostid;
	private Drules drules;
	private int status;
	private int lastup;
	private int lastdown;
	private Set dserviceses = new HashSet(0);

	public Dhosts() {
	}

	public Dhosts(long dhostid, Drules drules, int status, int lastup,
			int lastdown) {
		this.dhostid = dhostid;
		this.drules = drules;
		this.status = status;
		this.lastup = lastup;
		this.lastdown = lastdown;
	}

	public Dhosts(long dhostid, Drules drules, int status, int lastup,
			int lastdown, Set dserviceses) {
		this.dhostid = dhostid;
		this.drules = drules;
		this.status = status;
		this.lastup = lastup;
		this.lastdown = lastdown;
		this.dserviceses = dserviceses;
	}

	public long getDhostid() {
		return this.dhostid;
	}

	public void setDhostid(long dhostid) {
		this.dhostid = dhostid;
	}

	public Drules getDrules() {
		return this.drules;
	}

	public void setDrules(Drules drules) {
		this.drules = drules;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getLastup() {
		return this.lastup;
	}

	public void setLastup(int lastup) {
		this.lastup = lastup;
	}

	public int getLastdown() {
		return this.lastdown;
	}

	public void setLastdown(int lastdown) {
		this.lastdown = lastdown;
	}

	public Set getDserviceses() {
		return this.dserviceses;
	}

	public void setDserviceses(Set dserviceses) {
		this.dserviceses = dserviceses;
	}

}
