package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Dservices generated by hbm2java
 */
public class Dservices implements java.io.Serializable {

	private long dserviceid;
	private Dchecks dchecks;
	private Dhosts dhosts;
	private int type;
	private String key;
	private String value;
	private int port;
	private int status;
	private int lastup;
	private int lastdown;
	private String ip;
	private String dns;

	public Dservices() {
	}

	public Dservices(long dserviceid, Dchecks dchecks, Dhosts dhosts, int type,
			String key, String value, int port, int status, int lastup,
			int lastdown, String ip, String dns) {
		this.dserviceid = dserviceid;
		this.dchecks = dchecks;
		this.dhosts = dhosts;
		this.type = type;
		this.key = key;
		this.value = value;
		this.port = port;
		this.status = status;
		this.lastup = lastup;
		this.lastdown = lastdown;
		this.ip = ip;
		this.dns = dns;
	}

	public long getDserviceid() {
		return this.dserviceid;
	}

	public void setDserviceid(long dserviceid) {
		this.dserviceid = dserviceid;
	}

	public Dchecks getDchecks() {
		return this.dchecks;
	}

	public void setDchecks(Dchecks dchecks) {
		this.dchecks = dchecks;
	}

	public Dhosts getDhosts() {
		return this.dhosts;
	}

	public void setDhosts(Dhosts dhosts) {
		this.dhosts = dhosts;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getLastup() {
		return this.lastup;
	}

	public void setLastup(int lastup) {
		this.lastup = lastup;
	}

	public int getLastdown() {
		return this.lastdown;
	}

	public void setLastdown(int lastdown) {
		this.lastdown = lastdown;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

}
