package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Escalations generated by hbm2java
 */
public class Escalations implements java.io.Serializable {

	private long escalationid;
	private long actionid;
	private Long triggerid;
	private Long eventid;
	private Long REventid;
	private int nextcheck;
	private int escStep;
	private int status;
	private Long itemid;

	public Escalations() {
	}

	public Escalations(long escalationid, long actionid, int nextcheck,
			int escStep, int status) {
		this.escalationid = escalationid;
		this.actionid = actionid;
		this.nextcheck = nextcheck;
		this.escStep = escStep;
		this.status = status;
	}

	public Escalations(long escalationid, long actionid, Long triggerid,
			Long eventid, Long REventid, int nextcheck, int escStep,
			int status, Long itemid) {
		this.escalationid = escalationid;
		this.actionid = actionid;
		this.triggerid = triggerid;
		this.eventid = eventid;
		this.REventid = REventid;
		this.nextcheck = nextcheck;
		this.escStep = escStep;
		this.status = status;
		this.itemid = itemid;
	}

	public long getEscalationid() {
		return this.escalationid;
	}

	public void setEscalationid(long escalationid) {
		this.escalationid = escalationid;
	}

	public long getActionid() {
		return this.actionid;
	}

	public void setActionid(long actionid) {
		this.actionid = actionid;
	}

	public Long getTriggerid() {
		return this.triggerid;
	}

	public void setTriggerid(Long triggerid) {
		this.triggerid = triggerid;
	}

	public Long getEventid() {
		return this.eventid;
	}

	public void setEventid(Long eventid) {
		this.eventid = eventid;
	}

	public Long getREventid() {
		return this.REventid;
	}

	public void setREventid(Long REventid) {
		this.REventid = REventid;
	}

	public int getNextcheck() {
		return this.nextcheck;
	}

	public void setNextcheck(int nextcheck) {
		this.nextcheck = nextcheck;
	}

	public int getEscStep() {
		return this.escStep;
	}

	public void setEscStep(int escStep) {
		this.escStep = escStep;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getItemid() {
		return this.itemid;
	}

	public void setItemid(Long itemid) {
		this.itemid = itemid;
	}

}
