package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private long eventid;
	private int source;
	private int object;
	private long objectid;
	private int clock;
	private int value;
	private int acknowledged;
	private int ns;
	private Set alertses = new HashSet(0);
	private Set acknowledgeses = new HashSet(0);

	public Events() {
	}

	public Events(long eventid, int source, int object, long objectid,
			int clock, int value, int acknowledged, int ns) {
		this.eventid = eventid;
		this.source = source;
		this.object = object;
		this.objectid = objectid;
		this.clock = clock;
		this.value = value;
		this.acknowledged = acknowledged;
		this.ns = ns;
	}

	public Events(long eventid, int source, int object, long objectid,
			int clock, int value, int acknowledged, int ns, Set alertses,
			Set acknowledgeses) {
		this.eventid = eventid;
		this.source = source;
		this.object = object;
		this.objectid = objectid;
		this.clock = clock;
		this.value = value;
		this.acknowledged = acknowledged;
		this.ns = ns;
		this.alertses = alertses;
		this.acknowledgeses = acknowledgeses;
	}

	public long getEventid() {
		return this.eventid;
	}

	public void setEventid(long eventid) {
		this.eventid = eventid;
	}

	public int getSource() {
		return this.source;
	}

	public void setSource(int source) {
		this.source = source;
	}

	public int getObject() {
		return this.object;
	}

	public void setObject(int object) {
		this.object = object;
	}

	public long getObjectid() {
		return this.objectid;
	}

	public void setObjectid(long objectid) {
		this.objectid = objectid;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public int getAcknowledged() {
		return this.acknowledged;
	}

	public void setAcknowledged(int acknowledged) {
		this.acknowledged = acknowledged;
	}

	public int getNs() {
		return this.ns;
	}

	public void setNs(int ns) {
		this.ns = ns;
	}

	public Set getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set alertses) {
		this.alertses = alertses;
	}

	public Set getAcknowledgeses() {
		return this.acknowledgeses;
	}

	public void setAcknowledgeses(Set acknowledgeses) {
		this.acknowledgeses = acknowledgeses;
	}

}
