package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * EventA generated by hbm2java
 */
public class EventA implements java.io.Serializable {

	private long id;
	private Date date;
	private String title;

	public EventA() {
	}

	public EventA(long id) {
		this.id = id;
	}

	public EventA(long id, Date date, String title) {
		this.id = id;
		this.date = date;
		this.title = title;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
