package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Expressions generated by hbm2java
 */
public class Expressions implements java.io.Serializable {

	private long expressionid;
	private Regexps regexps;
	private String expression;
	private int expressionType;
	private String expDelimiter;
	private int caseSensitive;

	public Expressions() {
	}

	public Expressions(long expressionid, Regexps regexps, String expression,
			int expressionType, String expDelimiter, int caseSensitive) {
		this.expressionid = expressionid;
		this.regexps = regexps;
		this.expression = expression;
		this.expressionType = expressionType;
		this.expDelimiter = expDelimiter;
		this.caseSensitive = caseSensitive;
	}

	public long getExpressionid() {
		return this.expressionid;
	}

	public void setExpressionid(long expressionid) {
		this.expressionid = expressionid;
	}

	public Regexps getRegexps() {
		return this.regexps;
	}

	public void setRegexps(Regexps regexps) {
		this.regexps = regexps;
	}

	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	public int getExpressionType() {
		return this.expressionType;
	}

	public void setExpressionType(int expressionType) {
		this.expressionType = expressionType;
	}

	public String getExpDelimiter() {
		return this.expDelimiter;
	}

	public void setExpDelimiter(String expDelimiter) {
		this.expDelimiter = expDelimiter;
	}

	public int getCaseSensitive() {
		return this.caseSensitive;
	}

	public void setCaseSensitive(int caseSensitive) {
		this.caseSensitive = caseSensitive;
	}

}
