package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Functions generated by hbm2java
 */
public class Functions implements java.io.Serializable {

	private long functionid;
	private Items items;
	private Triggers triggers;
	private String function;
	private String parameter;

	public Functions() {
	}

	public Functions(long functionid, Items items, Triggers triggers,
			String function, String parameter) {
		this.functionid = functionid;
		this.items = items;
		this.triggers = triggers;
		this.function = function;
		this.parameter = parameter;
	}

	public long getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(long functionid) {
		this.functionid = functionid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public Triggers getTriggers() {
		return this.triggers;
	}

	public void setTriggers(Triggers triggers) {
		this.triggers = triggers;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

}
