package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Globalmacro generated by hbm2java
 */
public class Globalmacro implements java.io.Serializable {

	private long globalmacroid;
	private String macro;
	private String value;

	public Globalmacro() {
	}

	public Globalmacro(long globalmacroid, String macro, String value) {
		this.globalmacroid = globalmacroid;
		this.macro = macro;
		this.value = value;
	}

	public long getGlobalmacroid() {
		return this.globalmacroid;
	}

	public void setGlobalmacroid(long globalmacroid) {
		this.globalmacroid = globalmacroid;
	}

	public String getMacro() {
		return this.macro;
	}

	public void setMacro(String macro) {
		this.macro = macro;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
