package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Globalvars generated by hbm2java
 */
public class Globalvars implements java.io.Serializable {

	private long globalvarid;
	private int snmpLastsize;

	public Globalvars() {
	}

	public Globalvars(long globalvarid, int snmpLastsize) {
		this.globalvarid = globalvarid;
		this.snmpLastsize = snmpLastsize;
	}

	public long getGlobalvarid() {
		return this.globalvarid;
	}

	public void setGlobalvarid(long globalvarid) {
		this.globalvarid = globalvarid;
	}

	public int getSnmpLastsize() {
		return this.snmpLastsize;
	}

	public void setSnmpLastsize(int snmpLastsize) {
		this.snmpLastsize = snmpLastsize;
	}

}
