package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * GraphTheme generated by hbm2java
 */
public class GraphTheme implements java.io.Serializable {

	private long graphthemeid;
	private String theme;
	private String backgroundcolor;
	private String graphcolor;
	private String gridcolor;
	private String maingridcolor;
	private String gridbordercolor;
	private String textcolor;
	private String highlightcolor;
	private String leftpercentilecolor;
	private String rightpercentilecolor;
	private String nonworktimecolor;

	public GraphTheme() {
	}

	public GraphTheme(long graphthemeid, String theme, String backgroundcolor,
			String graphcolor, String gridcolor, String maingridcolor,
			String gridbordercolor, String textcolor, String highlightcolor,
			String leftpercentilecolor, String rightpercentilecolor,
			String nonworktimecolor) {
		this.graphthemeid = graphthemeid;
		this.theme = theme;
		this.backgroundcolor = backgroundcolor;
		this.graphcolor = graphcolor;
		this.gridcolor = gridcolor;
		this.maingridcolor = maingridcolor;
		this.gridbordercolor = gridbordercolor;
		this.textcolor = textcolor;
		this.highlightcolor = highlightcolor;
		this.leftpercentilecolor = leftpercentilecolor;
		this.rightpercentilecolor = rightpercentilecolor;
		this.nonworktimecolor = nonworktimecolor;
	}

	public long getGraphthemeid() {
		return this.graphthemeid;
	}

	public void setGraphthemeid(long graphthemeid) {
		this.graphthemeid = graphthemeid;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public String getBackgroundcolor() {
		return this.backgroundcolor;
	}

	public void setBackgroundcolor(String backgroundcolor) {
		this.backgroundcolor = backgroundcolor;
	}

	public String getGraphcolor() {
		return this.graphcolor;
	}

	public void setGraphcolor(String graphcolor) {
		this.graphcolor = graphcolor;
	}

	public String getGridcolor() {
		return this.gridcolor;
	}

	public void setGridcolor(String gridcolor) {
		this.gridcolor = gridcolor;
	}

	public String getMaingridcolor() {
		return this.maingridcolor;
	}

	public void setMaingridcolor(String maingridcolor) {
		this.maingridcolor = maingridcolor;
	}

	public String getGridbordercolor() {
		return this.gridbordercolor;
	}

	public void setGridbordercolor(String gridbordercolor) {
		this.gridbordercolor = gridbordercolor;
	}

	public String getTextcolor() {
		return this.textcolor;
	}

	public void setTextcolor(String textcolor) {
		this.textcolor = textcolor;
	}

	public String getHighlightcolor() {
		return this.highlightcolor;
	}

	public void setHighlightcolor(String highlightcolor) {
		this.highlightcolor = highlightcolor;
	}

	public String getLeftpercentilecolor() {
		return this.leftpercentilecolor;
	}

	public void setLeftpercentilecolor(String leftpercentilecolor) {
		this.leftpercentilecolor = leftpercentilecolor;
	}

	public String getRightpercentilecolor() {
		return this.rightpercentilecolor;
	}

	public void setRightpercentilecolor(String rightpercentilecolor) {
		this.rightpercentilecolor = rightpercentilecolor;
	}

	public String getNonworktimecolor() {
		return this.nonworktimecolor;
	}

	public void setNonworktimecolor(String nonworktimecolor) {
		this.nonworktimecolor = nonworktimecolor;
	}

}
