package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * GraphsItems generated by hbm2java
 */
public class GraphsItems implements java.io.Serializable {

	private long gitemid;
	private Items items;
	private Graphs graphs;
	private int drawtype;
	private int sortorder;
	private String color;
	private int yaxisside;
	private int calcFnc;
	private int type;

	public GraphsItems() {
	}

	public GraphsItems(long gitemid, Items items, Graphs graphs, int drawtype,
			int sortorder, String color, int yaxisside, int calcFnc, int type) {
		this.gitemid = gitemid;
		this.items = items;
		this.graphs = graphs;
		this.drawtype = drawtype;
		this.sortorder = sortorder;
		this.color = color;
		this.yaxisside = yaxisside;
		this.calcFnc = calcFnc;
		this.type = type;
	}

	public long getGitemid() {
		return this.gitemid;
	}

	public void setGitemid(long gitemid) {
		this.gitemid = gitemid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public Graphs getGraphs() {
		return this.graphs;
	}

	public void setGraphs(Graphs graphs) {
		this.graphs = graphs;
	}

	public int getDrawtype() {
		return this.drawtype;
	}

	public void setDrawtype(int drawtype) {
		this.drawtype = drawtype;
	}

	public int getSortorder() {
		return this.sortorder;
	}

	public void setSortorder(int sortorder) {
		this.sortorder = sortorder;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public int getYaxisside() {
		return this.yaxisside;
	}

	public void setYaxisside(int yaxisside) {
		this.yaxisside = yaxisside;
	}

	public int getCalcFnc() {
		return this.calcFnc;
	}

	public void setCalcFnc(int calcFnc) {
		this.calcFnc = calcFnc;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
