package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private long groupid;
	private String name;
	private int internal;
	private int flags;
	private Set groupPrototypes = new HashSet(0);
	private Set rightses = new HashSet(0);
	private Set configs = new HashSet(0);
	private Set opcommandGrps = new HashSet(0);
	private Set scriptses = new HashSet(0);
	private Set hostsGroupses = new HashSet(0);
	private GroupDiscovery groupDiscovery;
	private Set opgroups = new HashSet(0);
	private Set maintenancesGroupses = new HashSet(0);

	public Groups() {
	}

	public Groups(long groupid, String name, int internal, int flags) {
		this.groupid = groupid;
		this.name = name;
		this.internal = internal;
		this.flags = flags;
	}

	public Groups(long groupid, String name, int internal, int flags,
			Set groupPrototypes, Set rightses, Set configs, Set opcommandGrps,
			Set scriptses, Set hostsGroupses, GroupDiscovery groupDiscovery,
			Set opgroups, Set maintenancesGroupses) {
		this.groupid = groupid;
		this.name = name;
		this.internal = internal;
		this.flags = flags;
		this.groupPrototypes = groupPrototypes;
		this.rightses = rightses;
		this.configs = configs;
		this.opcommandGrps = opcommandGrps;
		this.scriptses = scriptses;
		this.hostsGroupses = hostsGroupses;
		this.groupDiscovery = groupDiscovery;
		this.opgroups = opgroups;
		this.maintenancesGroupses = maintenancesGroupses;
	}

	public long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(long groupid) {
		this.groupid = groupid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getInternal() {
		return this.internal;
	}

	public void setInternal(int internal) {
		this.internal = internal;
	}

	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	public Set getGroupPrototypes() {
		return this.groupPrototypes;
	}

	public void setGroupPrototypes(Set groupPrototypes) {
		this.groupPrototypes = groupPrototypes;
	}

	public Set getRightses() {
		return this.rightses;
	}

	public void setRightses(Set rightses) {
		this.rightses = rightses;
	}

	public Set getConfigs() {
		return this.configs;
	}

	public void setConfigs(Set configs) {
		this.configs = configs;
	}

	public Set getOpcommandGrps() {
		return this.opcommandGrps;
	}

	public void setOpcommandGrps(Set opcommandGrps) {
		this.opcommandGrps = opcommandGrps;
	}

	public Set getScriptses() {
		return this.scriptses;
	}

	public void setScriptses(Set scriptses) {
		this.scriptses = scriptses;
	}

	public Set getHostsGroupses() {
		return this.hostsGroupses;
	}

	public void setHostsGroupses(Set hostsGroupses) {
		this.hostsGroupses = hostsGroupses;
	}

	public GroupDiscovery getGroupDiscovery() {
		return this.groupDiscovery;
	}

	public void setGroupDiscovery(GroupDiscovery groupDiscovery) {
		this.groupDiscovery = groupDiscovery;
	}

	public Set getOpgroups() {
		return this.opgroups;
	}

	public void setOpgroups(Set opgroups) {
		this.opgroups = opgroups;
	}

	public Set getMaintenancesGroupses() {
		return this.maintenancesGroupses;
	}

	public void setMaintenancesGroupses(Set maintenancesGroupses) {
		this.maintenancesGroupses = maintenancesGroupses;
	}

}
