package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * GroupDiscovery generated by hbm2java
 */
public class GroupDiscovery implements java.io.Serializable {

	private long groupid;
	private Groups groups;
	private GroupPrototype groupPrototype;
	private String name;
	private int lastcheck;
	private int tsDelete;

	public GroupDiscovery() {
	}

	public GroupDiscovery(Groups groups, GroupPrototype groupPrototype,
			String name, int lastcheck, int tsDelete) {
		this.groups = groups;
		this.groupPrototype = groupPrototype;
		this.name = name;
		this.lastcheck = lastcheck;
		this.tsDelete = tsDelete;
	}

	public long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(long groupid) {
		this.groupid = groupid;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public GroupPrototype getGroupPrototype() {
		return this.groupPrototype;
	}

	public void setGroupPrototype(GroupPrototype groupPrototype) {
		this.groupPrototype = groupPrototype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getLastcheck() {
		return this.lastcheck;
	}

	public void setLastcheck(int lastcheck) {
		this.lastcheck = lastcheck;
	}

	public int getTsDelete() {
		return this.tsDelete;
	}

	public void setTsDelete(int tsDelete) {
		this.tsDelete = tsDelete;
	}

}
