package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * HistoryUint generated by hbm2java
 */
public class HistoryUint implements java.io.Serializable {

	private HistoryUintId id;

	public HistoryUint() {
	}

	public HistoryUint(HistoryUintId id) {
		this.id = id;
	}

	public HistoryUintId getId() {
		return this.id;
	}

	public void setId(HistoryUintId id) {
		this.id = id;
	}

}
