package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private HistoryId id;

	public History() {
	}

	public History(HistoryId id) {
		this.id = id;
	}

	public HistoryId getId() {
		return this.id;
	}

	public void setId(HistoryId id) {
		this.id = id;
	}

}
