package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * HistoryStr generated by hbm2java
 */
public class HistoryStr implements java.io.Serializable {

	private HistoryStrId id;

	public HistoryStr() {
	}

	public HistoryStr(HistoryStrId id) {
		this.id = id;
	}

	public HistoryStrId getId() {
		return this.id;
	}

	public void setId(HistoryStrId id) {
		this.id = id;
	}

}
