package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Hosts generated by hbm2java
 */
public class Hosts implements java.io.Serializable {

	private long hostid;
	private Hosts hostsByTemplateid;
	private Maintenances maintenances;
	private Hosts hostsByProxyHostid;
	private String host;
	private int status;
	private int disableUntil;
	private String error;
	private int available;
	private int errorsFrom;
	private int lastaccess;
	private int ipmiAuthtype;
	private int ipmiPrivilege;
	private String ipmiUsername;
	private String ipmiPassword;
	private int ipmiDisableUntil;
	private int ipmiAvailable;
	private int snmpDisableUntil;
	private int snmpAvailable;
	private int maintenanceStatus;
	private int maintenanceType;
	private int maintenanceFrom;
	private int ipmiErrorsFrom;
	private int snmpErrorsFrom;
	private String ipmiError;
	private String snmpError;
	private int jmxDisableUntil;
	private int jmxAvailable;
	private int jmxErrorsFrom;
	private String jmxError;
	private String name;
	private int flags;
	private String description;
	private int tlsConnect;
	private int tlsAccept;
	private String tlsIssuer;
	private String tlsSubject;
	private String tlsPskIdentity;
	private String tlsPsk;
	private Set autoregHosts = new HashSet(0);
	private Set hostsesForTemplateid = new HashSet(0);
	private Set hostsTemplatesesForHostid = new HashSet(0);
	private Set hostsesForProxyHostid = new HashSet(0);
	private HostDiscovery hostDiscoveryByHostid;
	private HostInventory hostInventory;
	private Set hostsTemplatesesForTemplateid = new HashSet(0);
	private Set hostDiscoveriesForParentHostid = new HashSet(0);
	private Set hostsGroupses = new HashSet(0);
	private Set interfaces = new HashSet(0);
	private Set httptests = new HashSet(0);
	private Set applicationses = new HashSet(0);
	private Set hostmacros = new HashSet(0);
	private Set druleses = new HashSet(0);
	private Set maintenancesHostses = new HashSet(0);
	private Set opcommandHsts = new HashSet(0);
	private Set groupPrototypes = new HashSet(0);
	private Set optemplates = new HashSet(0);
	private Set screenses = new HashSet(0);
	private Set itemses = new HashSet(0);

	public Hosts() {
	}

	public Hosts(long hostid, String host, int status, int disableUntil,
			String error, int available, int errorsFrom, int lastaccess,
			int ipmiAuthtype, int ipmiPrivilege, String ipmiUsername,
			String ipmiPassword, int ipmiDisableUntil, int ipmiAvailable,
			int snmpDisableUntil, int snmpAvailable, int maintenanceStatus,
			int maintenanceType, int maintenanceFrom, int ipmiErrorsFrom,
			int snmpErrorsFrom, String ipmiError, String snmpError,
			int jmxDisableUntil, int jmxAvailable, int jmxErrorsFrom,
			String jmxError, String name, int flags, String description,
			int tlsConnect, int tlsAccept, String tlsIssuer, String tlsSubject,
			String tlsPskIdentity, String tlsPsk) {
		this.hostid = hostid;
		this.host = host;
		this.status = status;
		this.disableUntil = disableUntil;
		this.error = error;
		this.available = available;
		this.errorsFrom = errorsFrom;
		this.lastaccess = lastaccess;
		this.ipmiAuthtype = ipmiAuthtype;
		this.ipmiPrivilege = ipmiPrivilege;
		this.ipmiUsername = ipmiUsername;
		this.ipmiPassword = ipmiPassword;
		this.ipmiDisableUntil = ipmiDisableUntil;
		this.ipmiAvailable = ipmiAvailable;
		this.snmpDisableUntil = snmpDisableUntil;
		this.snmpAvailable = snmpAvailable;
		this.maintenanceStatus = maintenanceStatus;
		this.maintenanceType = maintenanceType;
		this.maintenanceFrom = maintenanceFrom;
		this.ipmiErrorsFrom = ipmiErrorsFrom;
		this.snmpErrorsFrom = snmpErrorsFrom;
		this.ipmiError = ipmiError;
		this.snmpError = snmpError;
		this.jmxDisableUntil = jmxDisableUntil;
		this.jmxAvailable = jmxAvailable;
		this.jmxErrorsFrom = jmxErrorsFrom;
		this.jmxError = jmxError;
		this.name = name;
		this.flags = flags;
		this.description = description;
		this.tlsConnect = tlsConnect;
		this.tlsAccept = tlsAccept;
		this.tlsIssuer = tlsIssuer;
		this.tlsSubject = tlsSubject;
		this.tlsPskIdentity = tlsPskIdentity;
		this.tlsPsk = tlsPsk;
	}

	public Hosts(long hostid, Hosts hostsByTemplateid,
			Maintenances maintenances, Hosts hostsByProxyHostid, String host,
			int status, int disableUntil, String error, int available,
			int errorsFrom, int lastaccess, int ipmiAuthtype,
			int ipmiPrivilege, String ipmiUsername, String ipmiPassword,
			int ipmiDisableUntil, int ipmiAvailable, int snmpDisableUntil,
			int snmpAvailable, int maintenanceStatus, int maintenanceType,
			int maintenanceFrom, int ipmiErrorsFrom, int snmpErrorsFrom,
			String ipmiError, String snmpError, int jmxDisableUntil,
			int jmxAvailable, int jmxErrorsFrom, String jmxError, String name,
			int flags, String description, int tlsConnect, int tlsAccept,
			String tlsIssuer, String tlsSubject, String tlsPskIdentity,
			String tlsPsk, Set autoregHosts, Set hostsesForTemplateid,
			Set hostsTemplatesesForHostid, Set hostsesForProxyHostid,
			HostDiscovery hostDiscoveryByHostid, HostInventory hostInventory,
			Set hostsTemplatesesForTemplateid,
			Set hostDiscoveriesForParentHostid, Set hostsGroupses,
			Set interfaces, Set httptests, Set applicationses, Set hostmacros,
			Set druleses, Set maintenancesHostses, Set opcommandHsts,
			Set groupPrototypes, Set optemplates, Set screenses, Set itemses) {
		this.hostid = hostid;
		this.hostsByTemplateid = hostsByTemplateid;
		this.maintenances = maintenances;
		this.hostsByProxyHostid = hostsByProxyHostid;
		this.host = host;
		this.status = status;
		this.disableUntil = disableUntil;
		this.error = error;
		this.available = available;
		this.errorsFrom = errorsFrom;
		this.lastaccess = lastaccess;
		this.ipmiAuthtype = ipmiAuthtype;
		this.ipmiPrivilege = ipmiPrivilege;
		this.ipmiUsername = ipmiUsername;
		this.ipmiPassword = ipmiPassword;
		this.ipmiDisableUntil = ipmiDisableUntil;
		this.ipmiAvailable = ipmiAvailable;
		this.snmpDisableUntil = snmpDisableUntil;
		this.snmpAvailable = snmpAvailable;
		this.maintenanceStatus = maintenanceStatus;
		this.maintenanceType = maintenanceType;
		this.maintenanceFrom = maintenanceFrom;
		this.ipmiErrorsFrom = ipmiErrorsFrom;
		this.snmpErrorsFrom = snmpErrorsFrom;
		this.ipmiError = ipmiError;
		this.snmpError = snmpError;
		this.jmxDisableUntil = jmxDisableUntil;
		this.jmxAvailable = jmxAvailable;
		this.jmxErrorsFrom = jmxErrorsFrom;
		this.jmxError = jmxError;
		this.name = name;
		this.flags = flags;
		this.description = description;
		this.tlsConnect = tlsConnect;
		this.tlsAccept = tlsAccept;
		this.tlsIssuer = tlsIssuer;
		this.tlsSubject = tlsSubject;
		this.tlsPskIdentity = tlsPskIdentity;
		this.tlsPsk = tlsPsk;
		this.autoregHosts = autoregHosts;
		this.hostsesForTemplateid = hostsesForTemplateid;
		this.hostsTemplatesesForHostid = hostsTemplatesesForHostid;
		this.hostsesForProxyHostid = hostsesForProxyHostid;
		this.hostDiscoveryByHostid = hostDiscoveryByHostid;
		this.hostInventory = hostInventory;
		this.hostsTemplatesesForTemplateid = hostsTemplatesesForTemplateid;
		this.hostDiscoveriesForParentHostid = hostDiscoveriesForParentHostid;
		this.hostsGroupses = hostsGroupses;
		this.interfaces = interfaces;
		this.httptests = httptests;
		this.applicationses = applicationses;
		this.hostmacros = hostmacros;
		this.druleses = druleses;
		this.maintenancesHostses = maintenancesHostses;
		this.opcommandHsts = opcommandHsts;
		this.groupPrototypes = groupPrototypes;
		this.optemplates = optemplates;
		this.screenses = screenses;
		this.itemses = itemses;
	}

	public long getHostid() {
		return this.hostid;
	}

	public void setHostid(long hostid) {
		this.hostid = hostid;
	}

	public Hosts getHostsByTemplateid() {
		return this.hostsByTemplateid;
	}

	public void setHostsByTemplateid(Hosts hostsByTemplateid) {
		this.hostsByTemplateid = hostsByTemplateid;
	}

	public Maintenances getMaintenances() {
		return this.maintenances;
	}

	public void setMaintenances(Maintenances maintenances) {
		this.maintenances = maintenances;
	}

	public Hosts getHostsByProxyHostid() {
		return this.hostsByProxyHostid;
	}

	public void setHostsByProxyHostid(Hosts hostsByProxyHostid) {
		this.hostsByProxyHostid = hostsByProxyHostid;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getDisableUntil() {
		return this.disableUntil;
	}

	public void setDisableUntil(int disableUntil) {
		this.disableUntil = disableUntil;
	}

	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	public int getAvailable() {
		return this.available;
	}

	public void setAvailable(int available) {
		this.available = available;
	}

	public int getErrorsFrom() {
		return this.errorsFrom;
	}

	public void setErrorsFrom(int errorsFrom) {
		this.errorsFrom = errorsFrom;
	}

	public int getLastaccess() {
		return this.lastaccess;
	}

	public void setLastaccess(int lastaccess) {
		this.lastaccess = lastaccess;
	}

	public int getIpmiAuthtype() {
		return this.ipmiAuthtype;
	}

	public void setIpmiAuthtype(int ipmiAuthtype) {
		this.ipmiAuthtype = ipmiAuthtype;
	}

	public int getIpmiPrivilege() {
		return this.ipmiPrivilege;
	}

	public void setIpmiPrivilege(int ipmiPrivilege) {
		this.ipmiPrivilege = ipmiPrivilege;
	}

	public String getIpmiUsername() {
		return this.ipmiUsername;
	}

	public void setIpmiUsername(String ipmiUsername) {
		this.ipmiUsername = ipmiUsername;
	}

	public String getIpmiPassword() {
		return this.ipmiPassword;
	}

	public void setIpmiPassword(String ipmiPassword) {
		this.ipmiPassword = ipmiPassword;
	}

	public int getIpmiDisableUntil() {
		return this.ipmiDisableUntil;
	}

	public void setIpmiDisableUntil(int ipmiDisableUntil) {
		this.ipmiDisableUntil = ipmiDisableUntil;
	}

	public int getIpmiAvailable() {
		return this.ipmiAvailable;
	}

	public void setIpmiAvailable(int ipmiAvailable) {
		this.ipmiAvailable = ipmiAvailable;
	}

	public int getSnmpDisableUntil() {
		return this.snmpDisableUntil;
	}

	public void setSnmpDisableUntil(int snmpDisableUntil) {
		this.snmpDisableUntil = snmpDisableUntil;
	}

	public int getSnmpAvailable() {
		return this.snmpAvailable;
	}

	public void setSnmpAvailable(int snmpAvailable) {
		this.snmpAvailable = snmpAvailable;
	}

	public int getMaintenanceStatus() {
		return this.maintenanceStatus;
	}

	public void setMaintenanceStatus(int maintenanceStatus) {
		this.maintenanceStatus = maintenanceStatus;
	}

	public int getMaintenanceType() {
		return this.maintenanceType;
	}

	public void setMaintenanceType(int maintenanceType) {
		this.maintenanceType = maintenanceType;
	}

	public int getMaintenanceFrom() {
		return this.maintenanceFrom;
	}

	public void setMaintenanceFrom(int maintenanceFrom) {
		this.maintenanceFrom = maintenanceFrom;
	}

	public int getIpmiErrorsFrom() {
		return this.ipmiErrorsFrom;
	}

	public void setIpmiErrorsFrom(int ipmiErrorsFrom) {
		this.ipmiErrorsFrom = ipmiErrorsFrom;
	}

	public int getSnmpErrorsFrom() {
		return this.snmpErrorsFrom;
	}

	public void setSnmpErrorsFrom(int snmpErrorsFrom) {
		this.snmpErrorsFrom = snmpErrorsFrom;
	}

	public String getIpmiError() {
		return this.ipmiError;
	}

	public void setIpmiError(String ipmiError) {
		this.ipmiError = ipmiError;
	}

	public String getSnmpError() {
		return this.snmpError;
	}

	public void setSnmpError(String snmpError) {
		this.snmpError = snmpError;
	}

	public int getJmxDisableUntil() {
		return this.jmxDisableUntil;
	}

	public void setJmxDisableUntil(int jmxDisableUntil) {
		this.jmxDisableUntil = jmxDisableUntil;
	}

	public int getJmxAvailable() {
		return this.jmxAvailable;
	}

	public void setJmxAvailable(int jmxAvailable) {
		this.jmxAvailable = jmxAvailable;
	}

	public int getJmxErrorsFrom() {
		return this.jmxErrorsFrom;
	}

	public void setJmxErrorsFrom(int jmxErrorsFrom) {
		this.jmxErrorsFrom = jmxErrorsFrom;
	}

	public String getJmxError() {
		return this.jmxError;
	}

	public void setJmxError(String jmxError) {
		this.jmxError = jmxError;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTlsConnect() {
		return this.tlsConnect;
	}

	public void setTlsConnect(int tlsConnect) {
		this.tlsConnect = tlsConnect;
	}

	public int getTlsAccept() {
		return this.tlsAccept;
	}

	public void setTlsAccept(int tlsAccept) {
		this.tlsAccept = tlsAccept;
	}

	public String getTlsIssuer() {
		return this.tlsIssuer;
	}

	public void setTlsIssuer(String tlsIssuer) {
		this.tlsIssuer = tlsIssuer;
	}

	public String getTlsSubject() {
		return this.tlsSubject;
	}

	public void setTlsSubject(String tlsSubject) {
		this.tlsSubject = tlsSubject;
	}

	public String getTlsPskIdentity() {
		return this.tlsPskIdentity;
	}

	public void setTlsPskIdentity(String tlsPskIdentity) {
		this.tlsPskIdentity = tlsPskIdentity;
	}

	public String getTlsPsk() {
		return this.tlsPsk;
	}

	public void setTlsPsk(String tlsPsk) {
		this.tlsPsk = tlsPsk;
	}

	public Set getAutoregHosts() {
		return this.autoregHosts;
	}

	public void setAutoregHosts(Set autoregHosts) {
		this.autoregHosts = autoregHosts;
	}

	public Set getHostsesForTemplateid() {
		return this.hostsesForTemplateid;
	}

	public void setHostsesForTemplateid(Set hostsesForTemplateid) {
		this.hostsesForTemplateid = hostsesForTemplateid;
	}

	public Set getHostsTemplatesesForHostid() {
		return this.hostsTemplatesesForHostid;
	}

	public void setHostsTemplatesesForHostid(Set hostsTemplatesesForHostid) {
		this.hostsTemplatesesForHostid = hostsTemplatesesForHostid;
	}

	public Set getHostsesForProxyHostid() {
		return this.hostsesForProxyHostid;
	}

	public void setHostsesForProxyHostid(Set hostsesForProxyHostid) {
		this.hostsesForProxyHostid = hostsesForProxyHostid;
	}

	public HostDiscovery getHostDiscoveryByHostid() {
		return this.hostDiscoveryByHostid;
	}

	public void setHostDiscoveryByHostid(HostDiscovery hostDiscoveryByHostid) {
		this.hostDiscoveryByHostid = hostDiscoveryByHostid;
	}

	public HostInventory getHostInventory() {
		return this.hostInventory;
	}

	public void setHostInventory(HostInventory hostInventory) {
		this.hostInventory = hostInventory;
	}

	public Set getHostsTemplatesesForTemplateid() {
		return this.hostsTemplatesesForTemplateid;
	}

	public void setHostsTemplatesesForTemplateid(
			Set hostsTemplatesesForTemplateid) {
		this.hostsTemplatesesForTemplateid = hostsTemplatesesForTemplateid;
	}

	public Set getHostDiscoveriesForParentHostid() {
		return this.hostDiscoveriesForParentHostid;
	}

	public void setHostDiscoveriesForParentHostid(
			Set hostDiscoveriesForParentHostid) {
		this.hostDiscoveriesForParentHostid = hostDiscoveriesForParentHostid;
	}

	public Set getHostsGroupses() {
		return this.hostsGroupses;
	}

	public void setHostsGroupses(Set hostsGroupses) {
		this.hostsGroupses = hostsGroupses;
	}

	public Set getInterfaces() {
		return this.interfaces;
	}

	public void setInterfaces(Set interfaces) {
		this.interfaces = interfaces;
	}

	public Set getHttptests() {
		return this.httptests;
	}

	public void setHttptests(Set httptests) {
		this.httptests = httptests;
	}

	public Set getApplicationses() {
		return this.applicationses;
	}

	public void setApplicationses(Set applicationses) {
		this.applicationses = applicationses;
	}

	public Set getHostmacros() {
		return this.hostmacros;
	}

	public void setHostmacros(Set hostmacros) {
		this.hostmacros = hostmacros;
	}

	public Set getDruleses() {
		return this.druleses;
	}

	public void setDruleses(Set druleses) {
		this.druleses = druleses;
	}

	public Set getMaintenancesHostses() {
		return this.maintenancesHostses;
	}

	public void setMaintenancesHostses(Set maintenancesHostses) {
		this.maintenancesHostses = maintenancesHostses;
	}

	public Set getOpcommandHsts() {
		return this.opcommandHsts;
	}

	public void setOpcommandHsts(Set opcommandHsts) {
		this.opcommandHsts = opcommandHsts;
	}

	public Set getGroupPrototypes() {
		return this.groupPrototypes;
	}

	public void setGroupPrototypes(Set groupPrototypes) {
		this.groupPrototypes = groupPrototypes;
	}

	public Set getOptemplates() {
		return this.optemplates;
	}

	public void setOptemplates(Set optemplates) {
		this.optemplates = optemplates;
	}

	public Set getScreenses() {
		return this.screenses;
	}

	public void setScreenses(Set screenses) {
		this.screenses = screenses;
	}

	public Set getItemses() {
		return this.itemses;
	}

	public void setItemses(Set itemses) {
		this.itemses = itemses;
	}

}
