package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * HostInventory generated by hbm2java
 */
public class HostInventory implements java.io.Serializable {

	private long hostid;
	private Hosts hosts;
	private int inventoryMode;
	private String type;
	private String typeFull;
	private String name;
	private String alias;
	private String os;
	private String osFull;
	private String osShort;
	private String serialnoA;
	private String serialnoB;
	private String tag;
	private String assetTag;
	private String macaddressA;
	private String macaddressB;
	private String hardware;
	private String hardwareFull;
	private String software;
	private String softwareFull;
	private String softwareAppA;
	private String softwareAppB;
	private String softwareAppC;
	private String softwareAppD;
	private String softwareAppE;
	private String contact;
	private String location;
	private String locationLat;
	private String locationLon;
	private String notes;
	private String chassis;
	private String model;
	private String hwArch;
	private String vendor;
	private String contractNumber;
	private String installerName;
	private String deploymentStatus;
	private String urlA;
	private String urlB;
	private String urlC;
	private String hostNetworks;
	private String hostNetmask;
	private String hostRouter;
	private String oobIp;
	private String oobNetmask;
	private String oobRouter;
	private String dateHwPurchase;
	private String dateHwInstall;
	private String dateHwExpiry;
	private String dateHwDecomm;
	private String siteAddressA;
	private String siteAddressB;
	private String siteAddressC;
	private String siteCity;
	private String siteState;
	private String siteCountry;
	private String siteZip;
	private String siteRack;
	private String siteNotes;
	private String poc1Name;
	private String poc1Email;
	private String poc1PhoneA;
	private String poc1PhoneB;
	private String poc1Cell;
	private String poc1Screen;
	private String poc1Notes;
	private String poc2Name;
	private String poc2Email;
	private String poc2PhoneA;
	private String poc2PhoneB;
	private String poc2Cell;
	private String poc2Screen;
	private String poc2Notes;

	public HostInventory() {
	}

	public HostInventory(Hosts hosts, int inventoryMode, String type,
			String typeFull, String name, String alias, String os,
			String osFull, String osShort, String serialnoA, String serialnoB,
			String tag, String assetTag, String macaddressA,
			String macaddressB, String hardware, String hardwareFull,
			String software, String softwareFull, String softwareAppA,
			String softwareAppB, String softwareAppC, String softwareAppD,
			String softwareAppE, String contact, String location,
			String locationLat, String locationLon, String notes,
			String chassis, String model, String hwArch, String vendor,
			String contractNumber, String installerName,
			String deploymentStatus, String urlA, String urlB, String urlC,
			String hostNetworks, String hostNetmask, String hostRouter,
			String oobIp, String oobNetmask, String oobRouter,
			String dateHwPurchase, String dateHwInstall, String dateHwExpiry,
			String dateHwDecomm, String siteAddressA, String siteAddressB,
			String siteAddressC, String siteCity, String siteState,
			String siteCountry, String siteZip, String siteRack,
			String siteNotes, String poc1Name, String poc1Email,
			String poc1PhoneA, String poc1PhoneB, String poc1Cell,
			String poc1Screen, String poc1Notes, String poc2Name,
			String poc2Email, String poc2PhoneA, String poc2PhoneB,
			String poc2Cell, String poc2Screen, String poc2Notes) {
		this.hosts = hosts;
		this.inventoryMode = inventoryMode;
		this.type = type;
		this.typeFull = typeFull;
		this.name = name;
		this.alias = alias;
		this.os = os;
		this.osFull = osFull;
		this.osShort = osShort;
		this.serialnoA = serialnoA;
		this.serialnoB = serialnoB;
		this.tag = tag;
		this.assetTag = assetTag;
		this.macaddressA = macaddressA;
		this.macaddressB = macaddressB;
		this.hardware = hardware;
		this.hardwareFull = hardwareFull;
		this.software = software;
		this.softwareFull = softwareFull;
		this.softwareAppA = softwareAppA;
		this.softwareAppB = softwareAppB;
		this.softwareAppC = softwareAppC;
		this.softwareAppD = softwareAppD;
		this.softwareAppE = softwareAppE;
		this.contact = contact;
		this.location = location;
		this.locationLat = locationLat;
		this.locationLon = locationLon;
		this.notes = notes;
		this.chassis = chassis;
		this.model = model;
		this.hwArch = hwArch;
		this.vendor = vendor;
		this.contractNumber = contractNumber;
		this.installerName = installerName;
		this.deploymentStatus = deploymentStatus;
		this.urlA = urlA;
		this.urlB = urlB;
		this.urlC = urlC;
		this.hostNetworks = hostNetworks;
		this.hostNetmask = hostNetmask;
		this.hostRouter = hostRouter;
		this.oobIp = oobIp;
		this.oobNetmask = oobNetmask;
		this.oobRouter = oobRouter;
		this.dateHwPurchase = dateHwPurchase;
		this.dateHwInstall = dateHwInstall;
		this.dateHwExpiry = dateHwExpiry;
		this.dateHwDecomm = dateHwDecomm;
		this.siteAddressA = siteAddressA;
		this.siteAddressB = siteAddressB;
		this.siteAddressC = siteAddressC;
		this.siteCity = siteCity;
		this.siteState = siteState;
		this.siteCountry = siteCountry;
		this.siteZip = siteZip;
		this.siteRack = siteRack;
		this.siteNotes = siteNotes;
		this.poc1Name = poc1Name;
		this.poc1Email = poc1Email;
		this.poc1PhoneA = poc1PhoneA;
		this.poc1PhoneB = poc1PhoneB;
		this.poc1Cell = poc1Cell;
		this.poc1Screen = poc1Screen;
		this.poc1Notes = poc1Notes;
		this.poc2Name = poc2Name;
		this.poc2Email = poc2Email;
		this.poc2PhoneA = poc2PhoneA;
		this.poc2PhoneB = poc2PhoneB;
		this.poc2Cell = poc2Cell;
		this.poc2Screen = poc2Screen;
		this.poc2Notes = poc2Notes;
	}

	public long getHostid() {
		return this.hostid;
	}

	public void setHostid(long hostid) {
		this.hostid = hostid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public int getInventoryMode() {
		return this.inventoryMode;
	}

	public void setInventoryMode(int inventoryMode) {
		this.inventoryMode = inventoryMode;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTypeFull() {
		return this.typeFull;
	}

	public void setTypeFull(String typeFull) {
		this.typeFull = typeFull;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getOsFull() {
		return this.osFull;
	}

	public void setOsFull(String osFull) {
		this.osFull = osFull;
	}

	public String getOsShort() {
		return this.osShort;
	}

	public void setOsShort(String osShort) {
		this.osShort = osShort;
	}

	public String getSerialnoA() {
		return this.serialnoA;
	}

	public void setSerialnoA(String serialnoA) {
		this.serialnoA = serialnoA;
	}

	public String getSerialnoB() {
		return this.serialnoB;
	}

	public void setSerialnoB(String serialnoB) {
		this.serialnoB = serialnoB;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getAssetTag() {
		return this.assetTag;
	}

	public void setAssetTag(String assetTag) {
		this.assetTag = assetTag;
	}

	public String getMacaddressA() {
		return this.macaddressA;
	}

	public void setMacaddressA(String macaddressA) {
		this.macaddressA = macaddressA;
	}

	public String getMacaddressB() {
		return this.macaddressB;
	}

	public void setMacaddressB(String macaddressB) {
		this.macaddressB = macaddressB;
	}

	public String getHardware() {
		return this.hardware;
	}

	public void setHardware(String hardware) {
		this.hardware = hardware;
	}

	public String getHardwareFull() {
		return this.hardwareFull;
	}

	public void setHardwareFull(String hardwareFull) {
		this.hardwareFull = hardwareFull;
	}

	public String getSoftware() {
		return this.software;
	}

	public void setSoftware(String software) {
		this.software = software;
	}

	public String getSoftwareFull() {
		return this.softwareFull;
	}

	public void setSoftwareFull(String softwareFull) {
		this.softwareFull = softwareFull;
	}

	public String getSoftwareAppA() {
		return this.softwareAppA;
	}

	public void setSoftwareAppA(String softwareAppA) {
		this.softwareAppA = softwareAppA;
	}

	public String getSoftwareAppB() {
		return this.softwareAppB;
	}

	public void setSoftwareAppB(String softwareAppB) {
		this.softwareAppB = softwareAppB;
	}

	public String getSoftwareAppC() {
		return this.softwareAppC;
	}

	public void setSoftwareAppC(String softwareAppC) {
		this.softwareAppC = softwareAppC;
	}

	public String getSoftwareAppD() {
		return this.softwareAppD;
	}

	public void setSoftwareAppD(String softwareAppD) {
		this.softwareAppD = softwareAppD;
	}

	public String getSoftwareAppE() {
		return this.softwareAppE;
	}

	public void setSoftwareAppE(String softwareAppE) {
		this.softwareAppE = softwareAppE;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getLocationLat() {
		return this.locationLat;
	}

	public void setLocationLat(String locationLat) {
		this.locationLat = locationLat;
	}

	public String getLocationLon() {
		return this.locationLon;
	}

	public void setLocationLon(String locationLon) {
		this.locationLon = locationLon;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getChassis() {
		return this.chassis;
	}

	public void setChassis(String chassis) {
		this.chassis = chassis;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getHwArch() {
		return this.hwArch;
	}

	public void setHwArch(String hwArch) {
		this.hwArch = hwArch;
	}

	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	public String getContractNumber() {
		return this.contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	public String getInstallerName() {
		return this.installerName;
	}

	public void setInstallerName(String installerName) {
		this.installerName = installerName;
	}

	public String getDeploymentStatus() {
		return this.deploymentStatus;
	}

	public void setDeploymentStatus(String deploymentStatus) {
		this.deploymentStatus = deploymentStatus;
	}

	public String getUrlA() {
		return this.urlA;
	}

	public void setUrlA(String urlA) {
		this.urlA = urlA;
	}

	public String getUrlB() {
		return this.urlB;
	}

	public void setUrlB(String urlB) {
		this.urlB = urlB;
	}

	public String getUrlC() {
		return this.urlC;
	}

	public void setUrlC(String urlC) {
		this.urlC = urlC;
	}

	public String getHostNetworks() {
		return this.hostNetworks;
	}

	public void setHostNetworks(String hostNetworks) {
		this.hostNetworks = hostNetworks;
	}

	public String getHostNetmask() {
		return this.hostNetmask;
	}

	public void setHostNetmask(String hostNetmask) {
		this.hostNetmask = hostNetmask;
	}

	public String getHostRouter() {
		return this.hostRouter;
	}

	public void setHostRouter(String hostRouter) {
		this.hostRouter = hostRouter;
	}

	public String getOobIp() {
		return this.oobIp;
	}

	public void setOobIp(String oobIp) {
		this.oobIp = oobIp;
	}

	public String getOobNetmask() {
		return this.oobNetmask;
	}

	public void setOobNetmask(String oobNetmask) {
		this.oobNetmask = oobNetmask;
	}

	public String getOobRouter() {
		return this.oobRouter;
	}

	public void setOobRouter(String oobRouter) {
		this.oobRouter = oobRouter;
	}

	public String getDateHwPurchase() {
		return this.dateHwPurchase;
	}

	public void setDateHwPurchase(String dateHwPurchase) {
		this.dateHwPurchase = dateHwPurchase;
	}

	public String getDateHwInstall() {
		return this.dateHwInstall;
	}

	public void setDateHwInstall(String dateHwInstall) {
		this.dateHwInstall = dateHwInstall;
	}

	public String getDateHwExpiry() {
		return this.dateHwExpiry;
	}

	public void setDateHwExpiry(String dateHwExpiry) {
		this.dateHwExpiry = dateHwExpiry;
	}

	public String getDateHwDecomm() {
		return this.dateHwDecomm;
	}

	public void setDateHwDecomm(String dateHwDecomm) {
		this.dateHwDecomm = dateHwDecomm;
	}

	public String getSiteAddressA() {
		return this.siteAddressA;
	}

	public void setSiteAddressA(String siteAddressA) {
		this.siteAddressA = siteAddressA;
	}

	public String getSiteAddressB() {
		return this.siteAddressB;
	}

	public void setSiteAddressB(String siteAddressB) {
		this.siteAddressB = siteAddressB;
	}

	public String getSiteAddressC() {
		return this.siteAddressC;
	}

	public void setSiteAddressC(String siteAddressC) {
		this.siteAddressC = siteAddressC;
	}

	public String getSiteCity() {
		return this.siteCity;
	}

	public void setSiteCity(String siteCity) {
		this.siteCity = siteCity;
	}

	public String getSiteState() {
		return this.siteState;
	}

	public void setSiteState(String siteState) {
		this.siteState = siteState;
	}

	public String getSiteCountry() {
		return this.siteCountry;
	}

	public void setSiteCountry(String siteCountry) {
		this.siteCountry = siteCountry;
	}

	public String getSiteZip() {
		return this.siteZip;
	}

	public void setSiteZip(String siteZip) {
		this.siteZip = siteZip;
	}

	public String getSiteRack() {
		return this.siteRack;
	}

	public void setSiteRack(String siteRack) {
		this.siteRack = siteRack;
	}

	public String getSiteNotes() {
		return this.siteNotes;
	}

	public void setSiteNotes(String siteNotes) {
		this.siteNotes = siteNotes;
	}

	public String getPoc1Name() {
		return this.poc1Name;
	}

	public void setPoc1Name(String poc1Name) {
		this.poc1Name = poc1Name;
	}

	public String getPoc1Email() {
		return this.poc1Email;
	}

	public void setPoc1Email(String poc1Email) {
		this.poc1Email = poc1Email;
	}

	public String getPoc1PhoneA() {
		return this.poc1PhoneA;
	}

	public void setPoc1PhoneA(String poc1PhoneA) {
		this.poc1PhoneA = poc1PhoneA;
	}

	public String getPoc1PhoneB() {
		return this.poc1PhoneB;
	}

	public void setPoc1PhoneB(String poc1PhoneB) {
		this.poc1PhoneB = poc1PhoneB;
	}

	public String getPoc1Cell() {
		return this.poc1Cell;
	}

	public void setPoc1Cell(String poc1Cell) {
		this.poc1Cell = poc1Cell;
	}

	public String getPoc1Screen() {
		return this.poc1Screen;
	}

	public void setPoc1Screen(String poc1Screen) {
		this.poc1Screen = poc1Screen;
	}

	public String getPoc1Notes() {
		return this.poc1Notes;
	}

	public void setPoc1Notes(String poc1Notes) {
		this.poc1Notes = poc1Notes;
	}

	public String getPoc2Name() {
		return this.poc2Name;
	}

	public void setPoc2Name(String poc2Name) {
		this.poc2Name = poc2Name;
	}

	public String getPoc2Email() {
		return this.poc2Email;
	}

	public void setPoc2Email(String poc2Email) {
		this.poc2Email = poc2Email;
	}

	public String getPoc2PhoneA() {
		return this.poc2PhoneA;
	}

	public void setPoc2PhoneA(String poc2PhoneA) {
		this.poc2PhoneA = poc2PhoneA;
	}

	public String getPoc2PhoneB() {
		return this.poc2PhoneB;
	}

	public void setPoc2PhoneB(String poc2PhoneB) {
		this.poc2PhoneB = poc2PhoneB;
	}

	public String getPoc2Cell() {
		return this.poc2Cell;
	}

	public void setPoc2Cell(String poc2Cell) {
		this.poc2Cell = poc2Cell;
	}

	public String getPoc2Screen() {
		return this.poc2Screen;
	}

	public void setPoc2Screen(String poc2Screen) {
		this.poc2Screen = poc2Screen;
	}

	public String getPoc2Notes() {
		return this.poc2Notes;
	}

	public void setPoc2Notes(String poc2Notes) {
		this.poc2Notes = poc2Notes;
	}

}
