package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Hostmacro generated by hbm2java
 */
public class Hostmacro implements java.io.Serializable {

	private long hostmacroid;
	private Hosts hosts;
	private String macro;
	private String value;

	public Hostmacro() {
	}

	public Hostmacro(long hostmacroid, Hosts hosts, String macro, String value) {
		this.hostmacroid = hostmacroid;
		this.hosts = hosts;
		this.macro = macro;
		this.value = value;
	}

	public long getHostmacroid() {
		return this.hostmacroid;
	}

	public void setHostmacroid(long hostmacroid) {
		this.hostmacroid = hostmacroid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public String getMacro() {
		return this.macro;
	}

	public void setMacro(String macro) {
		this.macro = macro;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
