package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * HostDiscovery generated by hbm2java
 */
public class HostDiscovery implements java.io.Serializable {

	private long hostid;
	private Hosts hostsByHostid;
	private Hosts hostsByParentHostid;
	private Items items;
	private String host;
	private int lastcheck;
	private int tsDelete;

	public HostDiscovery() {
	}

	public HostDiscovery(Hosts hostsByHostid, String host, int lastcheck,
			int tsDelete) {
		this.hostsByHostid = hostsByHostid;
		this.host = host;
		this.lastcheck = lastcheck;
		this.tsDelete = tsDelete;
	}

	public HostDiscovery(Hosts hostsByHostid, Hosts hostsByParentHostid,
			Items items, String host, int lastcheck, int tsDelete) {
		this.hostsByHostid = hostsByHostid;
		this.hostsByParentHostid = hostsByParentHostid;
		this.items = items;
		this.host = host;
		this.lastcheck = lastcheck;
		this.tsDelete = tsDelete;
	}

	public long getHostid() {
		return this.hostid;
	}

	public void setHostid(long hostid) {
		this.hostid = hostid;
	}

	public Hosts getHostsByHostid() {
		return this.hostsByHostid;
	}

	public void setHostsByHostid(Hosts hostsByHostid) {
		this.hostsByHostid = hostsByHostid;
	}

	public Hosts getHostsByParentHostid() {
		return this.hostsByParentHostid;
	}

	public void setHostsByParentHostid(Hosts hostsByParentHostid) {
		this.hostsByParentHostid = hostsByParentHostid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public int getLastcheck() {
		return this.lastcheck;
	}

	public void setLastcheck(int lastcheck) {
		this.lastcheck = lastcheck;
	}

	public int getTsDelete() {
		return this.tsDelete;
	}

	public void setTsDelete(int tsDelete) {
		this.tsDelete = tsDelete;
	}

}
