package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * HostsGroups generated by hbm2java
 */
public class HostsGroups implements java.io.Serializable {

	private long hostgroupid;
	private Hosts hosts;
	private Groups groups;

	public HostsGroups() {
	}

	public HostsGroups(long hostgroupid, Hosts hosts, Groups groups) {
		this.hostgroupid = hostgroupid;
		this.hosts = hosts;
		this.groups = groups;
	}

	public long getHostgroupid() {
		return this.hostgroupid;
	}

	public void setHostgroupid(long hostgroupid) {
		this.hostgroupid = hostgroupid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

}
