package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Housekeeper generated by hbm2java
 */
public class Housekeeper implements java.io.Serializable {

	private long housekeeperid;
	private String tablename;
	private String field;
	private long value;

	public Housekeeper() {
	}

	public Housekeeper(long housekeeperid, String tablename, String field,
			long value) {
		this.housekeeperid = housekeeperid;
		this.tablename = tablename;
		this.field = field;
		this.value = value;
	}

	public long getHousekeeperid() {
		return this.housekeeperid;
	}

	public void setHousekeeperid(long housekeeperid) {
		this.housekeeperid = housekeeperid;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public long getValue() {
		return this.value;
	}

	public void setValue(long value) {
		this.value = value;
	}

}
