package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Httptest generated by hbm2java
 */
public class Httptest implements java.io.Serializable {

	private long httptestid;
	private Hosts hosts;
	private Httptest httptest;
	private Applications applications;
	private String name;
	private int nextcheck;
	private int delay;
	private int status;
	private String variables;
	private String agent;
	private int authentication;
	private String httpUser;
	private String httpPassword;
	private String httpProxy;
	private int retries;
	private String sslCertFile;
	private String sslKeyFile;
	private String sslKeyPassword;
	private int verifyPeer;
	private int verifyHost;
	private String headers;
	private Set httptestitems = new HashSet(0);
	private Set httpsteps = new HashSet(0);
	private Set httptests = new HashSet(0);

	public Httptest() {
	}

	public Httptest(long httptestid, Hosts hosts, String name, int nextcheck,
			int delay, int status, String variables, String agent,
			int authentication, String httpUser, String httpPassword,
			String httpProxy, int retries, String sslCertFile,
			String sslKeyFile, String sslKeyPassword, int verifyPeer,
			int verifyHost, String headers) {
		this.httptestid = httptestid;
		this.hosts = hosts;
		this.name = name;
		this.nextcheck = nextcheck;
		this.delay = delay;
		this.status = status;
		this.variables = variables;
		this.agent = agent;
		this.authentication = authentication;
		this.httpUser = httpUser;
		this.httpPassword = httpPassword;
		this.httpProxy = httpProxy;
		this.retries = retries;
		this.sslCertFile = sslCertFile;
		this.sslKeyFile = sslKeyFile;
		this.sslKeyPassword = sslKeyPassword;
		this.verifyPeer = verifyPeer;
		this.verifyHost = verifyHost;
		this.headers = headers;
	}

	public Httptest(long httptestid, Hosts hosts, Httptest httptest,
			Applications applications, String name, int nextcheck, int delay,
			int status, String variables, String agent, int authentication,
			String httpUser, String httpPassword, String httpProxy,
			int retries, String sslCertFile, String sslKeyFile,
			String sslKeyPassword, int verifyPeer, int verifyHost,
			String headers, Set httptestitems, Set httpsteps, Set httptests) {
		this.httptestid = httptestid;
		this.hosts = hosts;
		this.httptest = httptest;
		this.applications = applications;
		this.name = name;
		this.nextcheck = nextcheck;
		this.delay = delay;
		this.status = status;
		this.variables = variables;
		this.agent = agent;
		this.authentication = authentication;
		this.httpUser = httpUser;
		this.httpPassword = httpPassword;
		this.httpProxy = httpProxy;
		this.retries = retries;
		this.sslCertFile = sslCertFile;
		this.sslKeyFile = sslKeyFile;
		this.sslKeyPassword = sslKeyPassword;
		this.verifyPeer = verifyPeer;
		this.verifyHost = verifyHost;
		this.headers = headers;
		this.httptestitems = httptestitems;
		this.httpsteps = httpsteps;
		this.httptests = httptests;
	}

	public long getHttptestid() {
		return this.httptestid;
	}

	public void setHttptestid(long httptestid) {
		this.httptestid = httptestid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Httptest getHttptest() {
		return this.httptest;
	}

	public void setHttptest(Httptest httptest) {
		this.httptest = httptest;
	}

	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNextcheck() {
		return this.nextcheck;
	}

	public void setNextcheck(int nextcheck) {
		this.nextcheck = nextcheck;
	}

	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getVariables() {
		return this.variables;
	}

	public void setVariables(String variables) {
		this.variables = variables;
	}

	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	public int getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(int authentication) {
		this.authentication = authentication;
	}

	public String getHttpUser() {
		return this.httpUser;
	}

	public void setHttpUser(String httpUser) {
		this.httpUser = httpUser;
	}

	public String getHttpPassword() {
		return this.httpPassword;
	}

	public void setHttpPassword(String httpPassword) {
		this.httpPassword = httpPassword;
	}

	public String getHttpProxy() {
		return this.httpProxy;
	}

	public void setHttpProxy(String httpProxy) {
		this.httpProxy = httpProxy;
	}

	public int getRetries() {
		return this.retries;
	}

	public void setRetries(int retries) {
		this.retries = retries;
	}

	public String getSslCertFile() {
		return this.sslCertFile;
	}

	public void setSslCertFile(String sslCertFile) {
		this.sslCertFile = sslCertFile;
	}

	public String getSslKeyFile() {
		return this.sslKeyFile;
	}

	public void setSslKeyFile(String sslKeyFile) {
		this.sslKeyFile = sslKeyFile;
	}

	public String getSslKeyPassword() {
		return this.sslKeyPassword;
	}

	public void setSslKeyPassword(String sslKeyPassword) {
		this.sslKeyPassword = sslKeyPassword;
	}

	public int getVerifyPeer() {
		return this.verifyPeer;
	}

	public void setVerifyPeer(int verifyPeer) {
		this.verifyPeer = verifyPeer;
	}

	public int getVerifyHost() {
		return this.verifyHost;
	}

	public void setVerifyHost(int verifyHost) {
		this.verifyHost = verifyHost;
	}

	public String getHeaders() {
		return this.headers;
	}

	public void setHeaders(String headers) {
		this.headers = headers;
	}

	public Set getHttptestitems() {
		return this.httptestitems;
	}

	public void setHttptestitems(Set httptestitems) {
		this.httptestitems = httptestitems;
	}

	public Set getHttpsteps() {
		return this.httpsteps;
	}

	public void setHttpsteps(Set httpsteps) {
		this.httpsteps = httpsteps;
	}

	public Set getHttptests() {
		return this.httptests;
	}

	public void setHttptests(Set httptests) {
		this.httptests = httptests;
	}

}
