package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Httptestitem generated by hbm2java
 */
public class Httptestitem implements java.io.Serializable {

	private long httptestitemid;
	private Items items;
	private Httptest httptest;
	private int type;

	public Httptestitem() {
	}

	public Httptestitem(long httptestitemid, Items items, Httptest httptest,
			int type) {
		this.httptestitemid = httptestitemid;
		this.items = items;
		this.httptest = httptest;
		this.type = type;
	}

	public long getHttptestitemid() {
		return this.httptestitemid;
	}

	public void setHttptestitemid(long httptestitemid) {
		this.httptestitemid = httptestitemid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public Httptest getHttptest() {
		return this.httptest;
	}

	public void setHttptest(Httptest httptest) {
		this.httptest = httptest;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
