package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * IconMap generated by hbm2java
 */
public class IconMap implements java.io.Serializable {

	private long iconmapid;
	private Images images;
	private String name;
	private Set iconMappings = new HashSet(0);
	private Set sysmapses = new HashSet(0);

	public IconMap() {
	}

	public IconMap(long iconmapid, Images images, String name) {
		this.iconmapid = iconmapid;
		this.images = images;
		this.name = name;
	}

	public IconMap(long iconmapid, Images images, String name,
			Set iconMappings, Set sysmapses) {
		this.iconmapid = iconmapid;
		this.images = images;
		this.name = name;
		this.iconMappings = iconMappings;
		this.sysmapses = sysmapses;
	}

	public long getIconmapid() {
		return this.iconmapid;
	}

	public void setIconmapid(long iconmapid) {
		this.iconmapid = iconmapid;
	}

	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getIconMappings() {
		return this.iconMappings;
	}

	public void setIconMappings(Set iconMappings) {
		this.iconMappings = iconMappings;
	}

	public Set getSysmapses() {
		return this.sysmapses;
	}

	public void setSysmapses(Set sysmapses) {
		this.sysmapses = sysmapses;
	}

}
