package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * IconMapping generated by hbm2java
 */
public class IconMapping implements java.io.Serializable {

	private long iconmappingid;
	private Images images;
	private IconMap iconMap;
	private int inventoryLink;
	private String expression;
	private int sortorder;

	public IconMapping() {
	}

	public IconMapping(long iconmappingid, Images images, IconMap iconMap,
			int inventoryLink, String expression, int sortorder) {
		this.iconmappingid = iconmappingid;
		this.images = images;
		this.iconMap = iconMap;
		this.inventoryLink = inventoryLink;
		this.expression = expression;
		this.sortorder = sortorder;
	}

	public long getIconmappingid() {
		return this.iconmappingid;
	}

	public void setIconmappingid(long iconmappingid) {
		this.iconmappingid = iconmappingid;
	}

	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	public IconMap getIconMap() {
		return this.iconMap;
	}

	public void setIconMap(IconMap iconMap) {
		this.iconMap = iconMap;
	}

	public int getInventoryLink() {
		return this.inventoryLink;
	}

	public void setInventoryLink(int inventoryLink) {
		this.inventoryLink = inventoryLink;
	}

	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	public int getSortorder() {
		return this.sortorder;
	}

	public void setSortorder(int sortorder) {
		this.sortorder = sortorder;
	}

}
