package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Ids generated by hbm2java
 */
public class Ids implements java.io.Serializable {

	private IdsId id;
	private long nextid;

	public Ids() {
	}

	public Ids(IdsId id, long nextid) {
		this.id = id;
		this.nextid = nextid;
	}

	public IdsId getId() {
		return this.id;
	}

	public void setId(IdsId id) {
		this.id = id;
	}

	public long getNextid() {
		return this.nextid;
	}

	public void setNextid(long nextid) {
		this.nextid = nextid;
	}

}
