package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	private long imageid;
	private int imagetype;
	private String name;
	private byte[] image;
	private Set sysmapsElementsesForIconidOff = new HashSet(0);
	private Set sysmapsElementsesForIconidDisabled = new HashSet(0);
	private Set sysmapsElementsesForIconidOn = new HashSet(0);
	private Set iconMaps = new HashSet(0);
	private Set sysmapsElementsesForIconidMaintenance = new HashSet(0);
	private Set iconMappings = new HashSet(0);
	private Set sysmapses = new HashSet(0);

	public Images() {
	}

	public Images(long imageid, int imagetype, String name, byte[] image) {
		this.imageid = imageid;
		this.imagetype = imagetype;
		this.name = name;
		this.image = image;
	}

	public Images(long imageid, int imagetype, String name, byte[] image,
			Set sysmapsElementsesForIconidOff,
			Set sysmapsElementsesForIconidDisabled,
			Set sysmapsElementsesForIconidOn, Set iconMaps,
			Set sysmapsElementsesForIconidMaintenance, Set iconMappings,
			Set sysmapses) {
		this.imageid = imageid;
		this.imagetype = imagetype;
		this.name = name;
		this.image = image;
		this.sysmapsElementsesForIconidOff = sysmapsElementsesForIconidOff;
		this.sysmapsElementsesForIconidDisabled = sysmapsElementsesForIconidDisabled;
		this.sysmapsElementsesForIconidOn = sysmapsElementsesForIconidOn;
		this.iconMaps = iconMaps;
		this.sysmapsElementsesForIconidMaintenance = sysmapsElementsesForIconidMaintenance;
		this.iconMappings = iconMappings;
		this.sysmapses = sysmapses;
	}

	public long getImageid() {
		return this.imageid;
	}

	public void setImageid(long imageid) {
		this.imageid = imageid;
	}

	public int getImagetype() {
		return this.imagetype;
	}

	public void setImagetype(int imagetype) {
		this.imagetype = imagetype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Set getSysmapsElementsesForIconidOff() {
		return this.sysmapsElementsesForIconidOff;
	}

	public void setSysmapsElementsesForIconidOff(
			Set sysmapsElementsesForIconidOff) {
		this.sysmapsElementsesForIconidOff = sysmapsElementsesForIconidOff;
	}

	public Set getSysmapsElementsesForIconidDisabled() {
		return this.sysmapsElementsesForIconidDisabled;
	}

	public void setSysmapsElementsesForIconidDisabled(
			Set sysmapsElementsesForIconidDisabled) {
		this.sysmapsElementsesForIconidDisabled = sysmapsElementsesForIconidDisabled;
	}

	public Set getSysmapsElementsesForIconidOn() {
		return this.sysmapsElementsesForIconidOn;
	}

	public void setSysmapsElementsesForIconidOn(Set sysmapsElementsesForIconidOn) {
		this.sysmapsElementsesForIconidOn = sysmapsElementsesForIconidOn;
	}

	public Set getIconMaps() {
		return this.iconMaps;
	}

	public void setIconMaps(Set iconMaps) {
		this.iconMaps = iconMaps;
	}

	public Set getSysmapsElementsesForIconidMaintenance() {
		return this.sysmapsElementsesForIconidMaintenance;
	}

	public void setSysmapsElementsesForIconidMaintenance(
			Set sysmapsElementsesForIconidMaintenance) {
		this.sysmapsElementsesForIconidMaintenance = sysmapsElementsesForIconidMaintenance;
	}

	public Set getIconMappings() {
		return this.iconMappings;
	}

	public void setIconMappings(Set iconMappings) {
		this.iconMappings = iconMappings;
	}

	public Set getSysmapses() {
		return this.sysmapses;
	}

	public void setSysmapses(Set sysmapses) {
		this.sysmapses = sysmapses;
	}

}
