package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Interface generated by hbm2java
 */
public class Interface implements java.io.Serializable {

	private long interfaceid;
	private Hosts hosts;
	private int main;
	private int type;
	private int useip;
	private String ip;
	private String dns;
	private String port;
	private int bulk;
	private Set itemses = new HashSet(0);
	private Set interfaceDiscoveriesForParentInterfaceid = new HashSet(0);
	private InterfaceDiscovery interfaceDiscoveryByInterfaceid;

	public Interface() {
	}

	public Interface(long interfaceid, Hosts hosts, int main, int type,
			int useip, String ip, String dns, String port, int bulk) {
		this.interfaceid = interfaceid;
		this.hosts = hosts;
		this.main = main;
		this.type = type;
		this.useip = useip;
		this.ip = ip;
		this.dns = dns;
		this.port = port;
		this.bulk = bulk;
	}

	public Interface(long interfaceid, Hosts hosts, int main, int type,
			int useip, String ip, String dns, String port, int bulk,
			Set itemses, Set interfaceDiscoveriesForParentInterfaceid,
			InterfaceDiscovery interfaceDiscoveryByInterfaceid) {
		this.interfaceid = interfaceid;
		this.hosts = hosts;
		this.main = main;
		this.type = type;
		this.useip = useip;
		this.ip = ip;
		this.dns = dns;
		this.port = port;
		this.bulk = bulk;
		this.itemses = itemses;
		this.interfaceDiscoveriesForParentInterfaceid = interfaceDiscoveriesForParentInterfaceid;
		this.interfaceDiscoveryByInterfaceid = interfaceDiscoveryByInterfaceid;
	}

	public long getInterfaceid() {
		return this.interfaceid;
	}

	public void setInterfaceid(long interfaceid) {
		this.interfaceid = interfaceid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public int getMain() {
		return this.main;
	}

	public void setMain(int main) {
		this.main = main;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getUseip() {
		return this.useip;
	}

	public void setUseip(int useip) {
		this.useip = useip;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public int getBulk() {
		return this.bulk;
	}

	public void setBulk(int bulk) {
		this.bulk = bulk;
	}

	public Set getItemses() {
		return this.itemses;
	}

	public void setItemses(Set itemses) {
		this.itemses = itemses;
	}

	public Set getInterfaceDiscoveriesForParentInterfaceid() {
		return this.interfaceDiscoveriesForParentInterfaceid;
	}

	public void setInterfaceDiscoveriesForParentInterfaceid(
			Set interfaceDiscoveriesForParentInterfaceid) {
		this.interfaceDiscoveriesForParentInterfaceid = interfaceDiscoveriesForParentInterfaceid;
	}

	public InterfaceDiscovery getInterfaceDiscoveryByInterfaceid() {
		return this.interfaceDiscoveryByInterfaceid;
	}

	public void setInterfaceDiscoveryByInterfaceid(
			InterfaceDiscovery interfaceDiscoveryByInterfaceid) {
		this.interfaceDiscoveryByInterfaceid = interfaceDiscoveryByInterfaceid;
	}

}
