package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * InterfaceDiscovery generated by hbm2java
 */
public class InterfaceDiscovery implements java.io.Serializable {

	private long interfaceid;
	private Interface interfaceByInterfaceid;
	private Interface interfaceByParentInterfaceid;

	public InterfaceDiscovery() {
	}

	public InterfaceDiscovery(Interface interfaceByInterfaceid,
			Interface interfaceByParentInterfaceid) {
		this.interfaceByInterfaceid = interfaceByInterfaceid;
		this.interfaceByParentInterfaceid = interfaceByParentInterfaceid;
	}

	public long getInterfaceid() {
		return this.interfaceid;
	}

	public void setInterfaceid(long interfaceid) {
		this.interfaceid = interfaceid;
	}

	public Interface getInterfaceByInterfaceid() {
		return this.interfaceByInterfaceid;
	}

	public void setInterfaceByInterfaceid(Interface interfaceByInterfaceid) {
		this.interfaceByInterfaceid = interfaceByInterfaceid;
	}

	public Interface getInterfaceByParentInterfaceid() {
		return this.interfaceByParentInterfaceid;
	}

	public void setInterfaceByParentInterfaceid(
			Interface interfaceByParentInterfaceid) {
		this.interfaceByParentInterfaceid = interfaceByParentInterfaceid;
	}

}
