package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ItemCondition generated by hbm2java
 */
public class ItemCondition implements java.io.Serializable {

	private long itemConditionid;
	private Items items;
	private int operator;
	private String macro;
	private String value;

	public ItemCondition() {
	}

	public ItemCondition(long itemConditionid, Items items, int operator,
			String macro, String value) {
		this.itemConditionid = itemConditionid;
		this.items = items;
		this.operator = operator;
		this.macro = macro;
		this.value = value;
	}

	public long getItemConditionid() {
		return this.itemConditionid;
	}

	public void setItemConditionid(long itemConditionid) {
		this.itemConditionid = itemConditionid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public int getOperator() {
		return this.operator;
	}

	public void setOperator(int operator) {
		this.operator = operator;
	}

	public String getMacro() {
		return this.macro;
	}

	public void setMacro(String macro) {
		this.macro = macro;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
