package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ItemApplicationPrototype generated by hbm2java
 */
public class ItemApplicationPrototype implements java.io.Serializable {

	private long itemApplicationPrototypeid;
	private ApplicationPrototype applicationPrototype;
	private Items items;

	public ItemApplicationPrototype() {
	}

	public ItemApplicationPrototype(long itemApplicationPrototypeid,
			ApplicationPrototype applicationPrototype, Items items) {
		this.itemApplicationPrototypeid = itemApplicationPrototypeid;
		this.applicationPrototype = applicationPrototype;
		this.items = items;
	}

	public long getItemApplicationPrototypeid() {
		return this.itemApplicationPrototypeid;
	}

	public void setItemApplicationPrototypeid(long itemApplicationPrototypeid) {
		this.itemApplicationPrototypeid = itemApplicationPrototypeid;
	}

	public ApplicationPrototype getApplicationPrototype() {
		return this.applicationPrototype;
	}

	public void setApplicationPrototype(
			ApplicationPrototype applicationPrototype) {
		this.applicationPrototype = applicationPrototype;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

}
