package cn.com.esrichina.ServerMonitor.domain;
// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private long itemid;
     private Hosts hosts;
     private Valuemaps valuemaps;
     private Interface interfaceid;
     private Items items;
     private int type;
     private String snmpCommunity;
     private String snmpOid;
     private String name;
     private String key;
     private int delay;
     private int history;
     private int trends;
     private int status;
     private int valueType;
     private String trapperHosts;
     private String units;
     private int multiplier;
     private int delta;
     private String snmpv3Securityname;
     private int snmpv3Securitylevel;
     private String snmpv3Authpassphrase;
     private String snmpv3Privpassphrase;
     private String formula;
     private String error;
     private long lastlogsize;
     private String logtimefmt;
     private String delayFlex;
     private String params;
     private String ipmiSensor;
     private int dataType;
     private int authtype;
     private String username;
     private String password;
     private String publickey;
     private String privatekey;
     private int mtime;
     private int flags;
     private String port;
     private String description;
     private int inventoryLink;
     private String lifetime;
     private int snmpv3Authprotocol;
     private int snmpv3Privprotocol;
     private int state;
     private String snmpv3Contextname;
     private int evaltype;
     private Set functionses = new HashSet(0);
     private Set httptestitems = new HashSet(0);
     private Set hostDiscoveries = new HashSet(0);
     private Set itemConditions = new HashSet(0);
     private Set itemDiscoveriesForItemid = new HashSet(0);
     private Set itemApplicationPrototypes = new HashSet(0);
     private Set itemDiscoveriesForParentItemid = new HashSet(0);
     private Set applicationPrototypes = new HashSet(0);
     private Set graphsesForYminItemid = new HashSet(0);
     private Set graphsesForYmaxItemid = new HashSet(0);
     private Set graphsItemses = new HashSet(0);
     private Set httpstepitems = new HashSet(0);
     private Set itemsApplicationses = new HashSet(0);
     private Set itemses = new HashSet(0);

    public Items() {
    }

	
    public Items(long itemid, Hosts hosts, int type, String snmpCommunity, String snmpOid, String name, String key, int delay, int history, int trends, int status, int valueType, String trapperHosts, String units, int multiplier, int delta, String snmpv3Securityname, int snmpv3Securitylevel, String snmpv3Authpassphrase, String snmpv3Privpassphrase, String formula, String error, long lastlogsize, String logtimefmt, String delayFlex, String params, String ipmiSensor, int dataType, int authtype, String username, String password, String publickey, String privatekey, int mtime, int flags, String port, String description, int inventoryLink, String lifetime, int snmpv3Authprotocol, int snmpv3Privprotocol, int state, String snmpv3Contextname, int evaltype) {
        this.itemid = itemid;
        this.hosts = hosts;
        this.type = type;
        this.snmpCommunity = snmpCommunity;
        this.snmpOid = snmpOid;
        this.name = name;
        this.key = key;
        this.delay = delay;
        this.history = history;
        this.trends = trends;
        this.status = status;
        this.valueType = valueType;
        this.trapperHosts = trapperHosts;
        this.units = units;
        this.multiplier = multiplier;
        this.delta = delta;
        this.snmpv3Securityname = snmpv3Securityname;
        this.snmpv3Securitylevel = snmpv3Securitylevel;
        this.snmpv3Authpassphrase = snmpv3Authpassphrase;
        this.snmpv3Privpassphrase = snmpv3Privpassphrase;
        this.formula = formula;
        this.error = error;
        this.lastlogsize = lastlogsize;
        this.logtimefmt = logtimefmt;
        this.delayFlex = delayFlex;
        this.params = params;
        this.ipmiSensor = ipmiSensor;
        this.dataType = dataType;
        this.authtype = authtype;
        this.username = username;
        this.password = password;
        this.publickey = publickey;
        this.privatekey = privatekey;
        this.mtime = mtime;
        this.flags = flags;
        this.port = port;
        this.description = description;
        this.inventoryLink = inventoryLink;
        this.lifetime = lifetime;
        this.snmpv3Authprotocol = snmpv3Authprotocol;
        this.snmpv3Privprotocol = snmpv3Privprotocol;
        this.state = state;
        this.snmpv3Contextname = snmpv3Contextname;
        this.evaltype = evaltype;
    }
    public Items(long itemid, Hosts hosts, Valuemaps valuemaps, Interface interfaceid, Items items, int type, String snmpCommunity, String snmpOid, String name, String key, int delay, int history, int trends, int status, int valueType, String trapperHosts, String units, int multiplier, int delta, String snmpv3Securityname, int snmpv3Securitylevel, String snmpv3Authpassphrase, String snmpv3Privpassphrase, String formula, String error, long lastlogsize, String logtimefmt, String delayFlex, String params, String ipmiSensor, int dataType, int authtype, String username, String password, String publickey, String privatekey, int mtime, int flags, String port, String description, int inventoryLink, String lifetime, int snmpv3Authprotocol, int snmpv3Privprotocol, int state, String snmpv3Contextname, int evaltype, Set functionses, Set httptestitems, Set hostDiscoveries, Set itemConditions, Set itemDiscoveriesForItemid, Set itemApplicationPrototypes, Set itemDiscoveriesForParentItemid, Set applicationPrototypes, Set graphsesForYminItemid, Set graphsesForYmaxItemid, Set graphsItemses, Set httpstepitems, Set itemsApplicationses, Set itemses) {
       this.itemid = itemid;
       this.hosts = hosts;
       this.valuemaps = valuemaps;
       this.setInterfaceid(interfaceid);
       this.items = items;
       this.type = type;
       this.snmpCommunity = snmpCommunity;
       this.snmpOid = snmpOid;
       this.name = name;
       this.key = key;
       this.delay = delay;
       this.history = history;
       this.trends = trends;
       this.status = status;
       this.valueType = valueType;
       this.trapperHosts = trapperHosts;
       this.units = units;
       this.multiplier = multiplier;
       this.delta = delta;
       this.snmpv3Securityname = snmpv3Securityname;
       this.snmpv3Securitylevel = snmpv3Securitylevel;
       this.snmpv3Authpassphrase = snmpv3Authpassphrase;
       this.snmpv3Privpassphrase = snmpv3Privpassphrase;
       this.formula = formula;
       this.error = error;
       this.lastlogsize = lastlogsize;
       this.logtimefmt = logtimefmt;
       this.delayFlex = delayFlex;
       this.params = params;
       this.ipmiSensor = ipmiSensor;
       this.dataType = dataType;
       this.authtype = authtype;
       this.username = username;
       this.password = password;
       this.publickey = publickey;
       this.privatekey = privatekey;
       this.mtime = mtime;
       this.flags = flags;
       this.port = port;
       this.description = description;
       this.inventoryLink = inventoryLink;
       this.lifetime = lifetime;
       this.snmpv3Authprotocol = snmpv3Authprotocol;
       this.snmpv3Privprotocol = snmpv3Privprotocol;
       this.state = state;
       this.snmpv3Contextname = snmpv3Contextname;
       this.evaltype = evaltype;
       this.functionses = functionses;
       this.httptestitems = httptestitems;
       this.hostDiscoveries = hostDiscoveries;
       this.itemConditions = itemConditions;
       this.itemDiscoveriesForItemid = itemDiscoveriesForItemid;
       this.itemApplicationPrototypes = itemApplicationPrototypes;
       this.itemDiscoveriesForParentItemid = itemDiscoveriesForParentItemid;
       this.applicationPrototypes = applicationPrototypes;
       this.graphsesForYminItemid = graphsesForYminItemid;
       this.graphsesForYmaxItemid = graphsesForYmaxItemid;
       this.graphsItemses = graphsItemses;
       this.httpstepitems = httpstepitems;
       this.itemsApplicationses = itemsApplicationses;
       this.itemses = itemses;
    }
   
    public long getItemid() {
        return this.itemid;
    }
    
    public void setItemid(long itemid) {
        this.itemid = itemid;
    }
    public Hosts getHosts() {
        return this.hosts;
    }
    
    public void setHosts(Hosts hosts) {
        this.hosts = hosts;
    }
    public Valuemaps getValuemaps() {
        return this.valuemaps;
    }
    
    public void setValuemaps(Valuemaps valuemaps) {
        this.valuemaps = valuemaps;
    }

    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getSnmpCommunity() {
        return this.snmpCommunity;
    }
    
    public void setSnmpCommunity(String snmpCommunity) {
        this.snmpCommunity = snmpCommunity;
    }
    public String getSnmpOid() {
        return this.snmpOid;
    }
    
    public void setSnmpOid(String snmpOid) {
        this.snmpOid = snmpOid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public int getDelay() {
        return this.delay;
    }
    
    public void setDelay(int delay) {
        this.delay = delay;
    }
    public int getHistory() {
        return this.history;
    }
    
    public void setHistory(int history) {
        this.history = history;
    }
    public int getTrends() {
        return this.trends;
    }
    
    public void setTrends(int trends) {
        this.trends = trends;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public int getValueType() {
        return this.valueType;
    }
    
    public void setValueType(int valueType) {
        this.valueType = valueType;
    }
    public String getTrapperHosts() {
        return this.trapperHosts;
    }
    
    public void setTrapperHosts(String trapperHosts) {
        this.trapperHosts = trapperHosts;
    }
    public String getUnits() {
        return this.units;
    }
    
    public void setUnits(String units) {
        this.units = units;
    }
    public int getMultiplier() {
        return this.multiplier;
    }
    
    public void setMultiplier(int multiplier) {
        this.multiplier = multiplier;
    }
    public int getDelta() {
        return this.delta;
    }
    
    public void setDelta(int delta) {
        this.delta = delta;
    }
    public String getSnmpv3Securityname() {
        return this.snmpv3Securityname;
    }
    
    public void setSnmpv3Securityname(String snmpv3Securityname) {
        this.snmpv3Securityname = snmpv3Securityname;
    }
    public int getSnmpv3Securitylevel() {
        return this.snmpv3Securitylevel;
    }
    
    public void setSnmpv3Securitylevel(int snmpv3Securitylevel) {
        this.snmpv3Securitylevel = snmpv3Securitylevel;
    }
    public String getSnmpv3Authpassphrase() {
        return this.snmpv3Authpassphrase;
    }
    
    public void setSnmpv3Authpassphrase(String snmpv3Authpassphrase) {
        this.snmpv3Authpassphrase = snmpv3Authpassphrase;
    }
    public String getSnmpv3Privpassphrase() {
        return this.snmpv3Privpassphrase;
    }
    
    public void setSnmpv3Privpassphrase(String snmpv3Privpassphrase) {
        this.snmpv3Privpassphrase = snmpv3Privpassphrase;
    }
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    public long getLastlogsize() {
        return this.lastlogsize;
    }
    
    public void setLastlogsize(long lastlogsize) {
        this.lastlogsize = lastlogsize;
    }
    public String getLogtimefmt() {
        return this.logtimefmt;
    }
    
    public void setLogtimefmt(String logtimefmt) {
        this.logtimefmt = logtimefmt;
    }
    public String getDelayFlex() {
        return this.delayFlex;
    }
    
    public void setDelayFlex(String delayFlex) {
        this.delayFlex = delayFlex;
    }
    public String getParams() {
        return this.params;
    }
    
    public void setParams(String params) {
        this.params = params;
    }
    public String getIpmiSensor() {
        return this.ipmiSensor;
    }
    
    public void setIpmiSensor(String ipmiSensor) {
        this.ipmiSensor = ipmiSensor;
    }
    public int getDataType() {
        return this.dataType;
    }
    
    public void setDataType(int dataType) {
        this.dataType = dataType;
    }
    public int getAuthtype() {
        return this.authtype;
    }
    
    public void setAuthtype(int authtype) {
        this.authtype = authtype;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPublickey() {
        return this.publickey;
    }
    
    public void setPublickey(String publickey) {
        this.publickey = publickey;
    }
    public String getPrivatekey() {
        return this.privatekey;
    }
    
    public void setPrivatekey(String privatekey) {
        this.privatekey = privatekey;
    }
    public int getMtime() {
        return this.mtime;
    }
    
    public void setMtime(int mtime) {
        this.mtime = mtime;
    }
    public int getFlags() {
        return this.flags;
    }
    
    public void setFlags(int flags) {
        this.flags = flags;
    }
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getInventoryLink() {
        return this.inventoryLink;
    }
    
    public void setInventoryLink(int inventoryLink) {
        this.inventoryLink = inventoryLink;
    }
    public String getLifetime() {
        return this.lifetime;
    }
    
    public void setLifetime(String lifetime) {
        this.lifetime = lifetime;
    }
    public int getSnmpv3Authprotocol() {
        return this.snmpv3Authprotocol;
    }
    
    public void setSnmpv3Authprotocol(int snmpv3Authprotocol) {
        this.snmpv3Authprotocol = snmpv3Authprotocol;
    }
    public int getSnmpv3Privprotocol() {
        return this.snmpv3Privprotocol;
    }
    
    public void setSnmpv3Privprotocol(int snmpv3Privprotocol) {
        this.snmpv3Privprotocol = snmpv3Privprotocol;
    }
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }
    public String getSnmpv3Contextname() {
        return this.snmpv3Contextname;
    }
    
    public void setSnmpv3Contextname(String snmpv3Contextname) {
        this.snmpv3Contextname = snmpv3Contextname;
    }
    public int getEvaltype() {
        return this.evaltype;
    }
    
    public void setEvaltype(int evaltype) {
        this.evaltype = evaltype;
    }
    public Set getFunctionses() {
        return this.functionses;
    }
    
    public void setFunctionses(Set functionses) {
        this.functionses = functionses;
    }
    public Set getHttptestitems() {
        return this.httptestitems;
    }
    
    public void setHttptestitems(Set httptestitems) {
        this.httptestitems = httptestitems;
    }
    public Set getHostDiscoveries() {
        return this.hostDiscoveries;
    }
    
    public void setHostDiscoveries(Set hostDiscoveries) {
        this.hostDiscoveries = hostDiscoveries;
    }
    public Set getItemConditions() {
        return this.itemConditions;
    }
    
    public void setItemConditions(Set itemConditions) {
        this.itemConditions = itemConditions;
    }
    public Set getItemDiscoveriesForItemid() {
        return this.itemDiscoveriesForItemid;
    }
    
    public void setItemDiscoveriesForItemid(Set itemDiscoveriesForItemid) {
        this.itemDiscoveriesForItemid = itemDiscoveriesForItemid;
    }
    public Set getItemApplicationPrototypes() {
        return this.itemApplicationPrototypes;
    }
    
    public void setItemApplicationPrototypes(Set itemApplicationPrototypes) {
        this.itemApplicationPrototypes = itemApplicationPrototypes;
    }
    public Set getItemDiscoveriesForParentItemid() {
        return this.itemDiscoveriesForParentItemid;
    }
    
    public void setItemDiscoveriesForParentItemid(Set itemDiscoveriesForParentItemid) {
        this.itemDiscoveriesForParentItemid = itemDiscoveriesForParentItemid;
    }
    public Set getApplicationPrototypes() {
        return this.applicationPrototypes;
    }
    
    public void setApplicationPrototypes(Set applicationPrototypes) {
        this.applicationPrototypes = applicationPrototypes;
    }
    public Set getGraphsesForYminItemid() {
        return this.graphsesForYminItemid;
    }
    
    public void setGraphsesForYminItemid(Set graphsesForYminItemid) {
        this.graphsesForYminItemid = graphsesForYminItemid;
    }
    public Set getGraphsesForYmaxItemid() {
        return this.graphsesForYmaxItemid;
    }
    
    public void setGraphsesForYmaxItemid(Set graphsesForYmaxItemid) {
        this.graphsesForYmaxItemid = graphsesForYmaxItemid;
    }
    public Set getGraphsItemses() {
        return this.graphsItemses;
    }
    
    public void setGraphsItemses(Set graphsItemses) {
        this.graphsItemses = graphsItemses;
    }
    public Set getHttpstepitems() {
        return this.httpstepitems;
    }
    
    public void setHttpstepitems(Set httpstepitems) {
        this.httpstepitems = httpstepitems;
    }
    public Set getItemsApplicationses() {
        return this.itemsApplicationses;
    }
    
    public void setItemsApplicationses(Set itemsApplicationses) {
        this.itemsApplicationses = itemsApplicationses;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }


	public Interface getInterfaceid() {
		return interfaceid;
	}


	public void setInterfaceid(Interface interfaceid) {
		this.interfaceid = interfaceid;
	}

	@Override
	public String toString() {
		return "["+this.itemid+this.hosts.getHostid()+this.name+this.key+"]";
	}


}


