package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ItemDiscovery generated by hbm2java
 */
public class ItemDiscovery implements java.io.Serializable {

	private long itemdiscoveryid;
	private Items itemsByItemid;
	private Items itemsByParentItemid;
	private String key;
	private int lastcheck;
	private int tsDelete;

	public ItemDiscovery() {
	}

	public ItemDiscovery(long itemdiscoveryid, Items itemsByItemid,
			Items itemsByParentItemid, String key, int lastcheck, int tsDelete) {
		this.itemdiscoveryid = itemdiscoveryid;
		this.itemsByItemid = itemsByItemid;
		this.itemsByParentItemid = itemsByParentItemid;
		this.key = key;
		this.lastcheck = lastcheck;
		this.tsDelete = tsDelete;
	}

	public long getItemdiscoveryid() {
		return this.itemdiscoveryid;
	}

	public void setItemdiscoveryid(long itemdiscoveryid) {
		this.itemdiscoveryid = itemdiscoveryid;
	}

	public Items getItemsByItemid() {
		return this.itemsByItemid;
	}

	public void setItemsByItemid(Items itemsByItemid) {
		this.itemsByItemid = itemsByItemid;
	}

	public Items getItemsByParentItemid() {
		return this.itemsByParentItemid;
	}

	public void setItemsByParentItemid(Items itemsByParentItemid) {
		this.itemsByParentItemid = itemsByParentItemid;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public int getLastcheck() {
		return this.lastcheck;
	}

	public void setLastcheck(int lastcheck) {
		this.lastcheck = lastcheck;
	}

	public int getTsDelete() {
		return this.tsDelete;
	}

	public void setTsDelete(int tsDelete) {
		this.tsDelete = tsDelete;
	}

}
