package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ItemsApplications generated by hbm2java
 */
public class ItemsApplications implements java.io.Serializable {

	private long itemappid;
	private Items items;
	private Applications applications;

	public ItemsApplications() {
	}

	public ItemsApplications(long itemappid, Items items,
			Applications applications) {
		this.itemappid = itemappid;
		this.items = items;
		this.applications = applications;
	}

	public long getItemappid() {
		return this.itemappid;
	}

	public void setItemappid(long itemappid) {
		this.itemappid = itemappid;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

}
