package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * MaintenancesWindows generated by hbm2java
 */
public class MaintenancesWindows implements java.io.Serializable {

	private long maintenanceTimeperiodid;
	private Maintenances maintenances;
	private Timeperiods timeperiods;

	public MaintenancesWindows() {
	}

	public MaintenancesWindows(long maintenanceTimeperiodid,
			Maintenances maintenances, Timeperiods timeperiods) {
		this.maintenanceTimeperiodid = maintenanceTimeperiodid;
		this.maintenances = maintenances;
		this.timeperiods = timeperiods;
	}

	public long getMaintenanceTimeperiodid() {
		return this.maintenanceTimeperiodid;
	}

	public void setMaintenanceTimeperiodid(long maintenanceTimeperiodid) {
		this.maintenanceTimeperiodid = maintenanceTimeperiodid;
	}

	public Maintenances getMaintenances() {
		return this.maintenances;
	}

	public void setMaintenances(Maintenances maintenances) {
		this.maintenances = maintenances;
	}

	public Timeperiods getTimeperiods() {
		return this.timeperiods;
	}

	public void setTimeperiods(Timeperiods timeperiods) {
		this.timeperiods = timeperiods;
	}

}
