package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * MaintenancesGroups generated by hbm2java
 */
public class MaintenancesGroups implements java.io.Serializable {

	private long maintenanceGroupid;
	private Maintenances maintenances;
	private Groups groups;

	public MaintenancesGroups() {
	}

	public MaintenancesGroups(long maintenanceGroupid,
			Maintenances maintenances, Groups groups) {
		this.maintenanceGroupid = maintenanceGroupid;
		this.maintenances = maintenances;
		this.groups = groups;
	}

	public long getMaintenanceGroupid() {
		return this.maintenanceGroupid;
	}

	public void setMaintenanceGroupid(long maintenanceGroupid) {
		this.maintenanceGroupid = maintenanceGroupid;
	}

	public Maintenances getMaintenances() {
		return this.maintenances;
	}

	public void setMaintenances(Maintenances maintenances) {
		this.maintenances = maintenances;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

}
