package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Maintenances generated by hbm2java
 */
public class Maintenances implements java.io.Serializable {

	private long maintenanceid;
	private String name;
	private int maintenanceType;
	private String description;
	private int activeSince;
	private int activeTill;
	private Set maintenancesHostses = new HashSet(0);
	private Set hostses = new HashSet(0);
	private Set maintenancesWindowses = new HashSet(0);
	private Set maintenancesGroupses = new HashSet(0);

	public Maintenances() {
	}

	public Maintenances(long maintenanceid, String name, int maintenanceType,
			String description, int activeSince, int activeTill) {
		this.maintenanceid = maintenanceid;
		this.name = name;
		this.maintenanceType = maintenanceType;
		this.description = description;
		this.activeSince = activeSince;
		this.activeTill = activeTill;
	}

	public Maintenances(long maintenanceid, String name, int maintenanceType,
			String description, int activeSince, int activeTill,
			Set maintenancesHostses, Set hostses, Set maintenancesWindowses,
			Set maintenancesGroupses) {
		this.maintenanceid = maintenanceid;
		this.name = name;
		this.maintenanceType = maintenanceType;
		this.description = description;
		this.activeSince = activeSince;
		this.activeTill = activeTill;
		this.maintenancesHostses = maintenancesHostses;
		this.hostses = hostses;
		this.maintenancesWindowses = maintenancesWindowses;
		this.maintenancesGroupses = maintenancesGroupses;
	}

	public long getMaintenanceid() {
		return this.maintenanceid;
	}

	public void setMaintenanceid(long maintenanceid) {
		this.maintenanceid = maintenanceid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getMaintenanceType() {
		return this.maintenanceType;
	}

	public void setMaintenanceType(int maintenanceType) {
		this.maintenanceType = maintenanceType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getActiveSince() {
		return this.activeSince;
	}

	public void setActiveSince(int activeSince) {
		this.activeSince = activeSince;
	}

	public int getActiveTill() {
		return this.activeTill;
	}

	public void setActiveTill(int activeTill) {
		this.activeTill = activeTill;
	}

	public Set getMaintenancesHostses() {
		return this.maintenancesHostses;
	}

	public void setMaintenancesHostses(Set maintenancesHostses) {
		this.maintenancesHostses = maintenancesHostses;
	}

	public Set getHostses() {
		return this.hostses;
	}

	public void setHostses(Set hostses) {
		this.hostses = hostses;
	}

	public Set getMaintenancesWindowses() {
		return this.maintenancesWindowses;
	}

	public void setMaintenancesWindowses(Set maintenancesWindowses) {
		this.maintenancesWindowses = maintenancesWindowses;
	}

	public Set getMaintenancesGroupses() {
		return this.maintenancesGroupses;
	}

	public void setMaintenancesGroupses(Set maintenancesGroupses) {
		this.maintenancesGroupses = maintenancesGroupses;
	}

}
