package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Mappings generated by hbm2java
 */
public class Mappings implements java.io.Serializable {

	private long mappingid;
	private Valuemaps valuemaps;
	private String value;
	private String newvalue;

	public Mappings() {
	}

	public Mappings(long mappingid, Valuemaps valuemaps, String value,
			String newvalue) {
		this.mappingid = mappingid;
		this.valuemaps = valuemaps;
		this.value = value;
		this.newvalue = newvalue;
	}

	public long getMappingid() {
		return this.mappingid;
	}

	public void setMappingid(long mappingid) {
		this.mappingid = mappingid;
	}

	public Valuemaps getValuemaps() {
		return this.valuemaps;
	}

	public void setValuemaps(Valuemaps valuemaps) {
		this.valuemaps = valuemaps;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(String newvalue) {
		this.newvalue = newvalue;
	}

}
