package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Media generated by hbm2java
 */
public class Media implements java.io.Serializable {

	private long mediaid;
	private MediaType mediaType;
	private Users users;
	private String sendto;
	private int active;
	private int severity;
	private String period;

	public Media() {
	}

	public Media(long mediaid, MediaType mediaType, Users users, String sendto,
			int active, int severity, String period) {
		this.mediaid = mediaid;
		this.mediaType = mediaType;
		this.users = users;
		this.sendto = sendto;
		this.active = active;
		this.severity = severity;
		this.period = period;
	}

	public long getMediaid() {
		return this.mediaid;
	}

	public void setMediaid(long mediaid) {
		this.mediaid = mediaid;
	}

	public MediaType getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(MediaType mediaType) {
		this.mediaType = mediaType;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getSendto() {
		return this.sendto;
	}

	public void setSendto(String sendto) {
		this.sendto = sendto;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public int getSeverity() {
		return this.severity;
	}

	public void setSeverity(int severity) {
		this.severity = severity;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

}
