package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * OpcommandHst generated by hbm2java
 */
public class OpcommandHst implements java.io.Serializable {

	private long opcommandHstid;
	private Hosts hosts;
	private Operations operations;

	public OpcommandHst() {
	}

	public OpcommandHst(long opcommandHstid, Operations operations) {
		this.opcommandHstid = opcommandHstid;
		this.operations = operations;
	}

	public OpcommandHst(long opcommandHstid, Hosts hosts, Operations operations) {
		this.opcommandHstid = opcommandHstid;
		this.hosts = hosts;
		this.operations = operations;
	}

	public long getOpcommandHstid() {
		return this.opcommandHstid;
	}

	public void setOpcommandHstid(long opcommandHstid) {
		this.opcommandHstid = opcommandHstid;
	}

	public Hosts getHosts() {
		return this.hosts;
	}

	public void setHosts(Hosts hosts) {
		this.hosts = hosts;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

}
