package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * OpcommandGrp generated by hbm2java
 */
public class OpcommandGrp implements java.io.Serializable {

	private long opcommandGrpid;
	private Operations operations;
	private Groups groups;

	public OpcommandGrp() {
	}

	public OpcommandGrp(long opcommandGrpid, Operations operations,
			Groups groups) {
		this.opcommandGrpid = opcommandGrpid;
		this.operations = operations;
		this.groups = groups;
	}

	public long getOpcommandGrpid() {
		return this.opcommandGrpid;
	}

	public void setOpcommandGrpid(long opcommandGrpid) {
		this.opcommandGrpid = opcommandGrpid;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

}
