package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Opcommand generated by hbm2java
 */
public class Opcommand implements java.io.Serializable {

	private long operationid;
	private Scripts scripts;
	private Operations operations;
	private int type;
	private int executeOn;
	private String port;
	private int authtype;
	private String username;
	private String password;
	private String publickey;
	private String privatekey;
	private String command;

	public Opcommand() {
	}

	public Opcommand(Operations operations, int type, int executeOn,
			String port, int authtype, String username, String password,
			String publickey, String privatekey, String command) {
		this.operations = operations;
		this.type = type;
		this.executeOn = executeOn;
		this.port = port;
		this.authtype = authtype;
		this.username = username;
		this.password = password;
		this.publickey = publickey;
		this.privatekey = privatekey;
		this.command = command;
	}

	public Opcommand(Scripts scripts, Operations operations, int type,
			int executeOn, String port, int authtype, String username,
			String password, String publickey, String privatekey, String command) {
		this.scripts = scripts;
		this.operations = operations;
		this.type = type;
		this.executeOn = executeOn;
		this.port = port;
		this.authtype = authtype;
		this.username = username;
		this.password = password;
		this.publickey = publickey;
		this.privatekey = privatekey;
		this.command = command;
	}

	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	public Scripts getScripts() {
		return this.scripts;
	}

	public void setScripts(Scripts scripts) {
		this.scripts = scripts;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getExecuteOn() {
		return this.executeOn;
	}

	public void setExecuteOn(int executeOn) {
		this.executeOn = executeOn;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public int getAuthtype() {
		return this.authtype;
	}

	public void setAuthtype(int authtype) {
		this.authtype = authtype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPublickey() {
		return this.publickey;
	}

	public void setPublickey(String publickey) {
		this.publickey = publickey;
	}

	public String getPrivatekey() {
		return this.privatekey;
	}

	public void setPrivatekey(String privatekey) {
		this.privatekey = privatekey;
	}

	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

}
