package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Operations generated by hbm2java
 */
public class Operations implements java.io.Serializable {

	private long operationid;
	private Actions actions;
	private int operationtype;
	private int escPeriod;
	private int escStepFrom;
	private int escStepTo;
	private int evaltype;
	private Opmessage opmessage;
	private Set opmessageGrps = new HashSet(0);
	private Set opconditionses = new HashSet(0);
	private Set opcommandHsts = new HashSet(0);
	private Set opcommandGrps = new HashSet(0);
	private Set opmessageUsrs = new HashSet(0);
	private Set opgroups = new HashSet(0);
	private Set optemplates = new HashSet(0);
	private Opcommand opcommand;
	private Opinventory opinventory;

	public Operations() {
	}

	public Operations(long operationid, Actions actions, int operationtype,
			int escPeriod, int escStepFrom, int escStepTo, int evaltype) {
		this.operationid = operationid;
		this.actions = actions;
		this.operationtype = operationtype;
		this.escPeriod = escPeriod;
		this.escStepFrom = escStepFrom;
		this.escStepTo = escStepTo;
		this.evaltype = evaltype;
	}

	public Operations(long operationid, Actions actions, int operationtype,
			int escPeriod, int escStepFrom, int escStepTo, int evaltype,
			Opmessage opmessage, Set opmessageGrps, Set opconditionses,
			Set opcommandHsts, Set opcommandGrps, Set opmessageUsrs,
			Set opgroups, Set optemplates, Opcommand opcommand,
			Opinventory opinventory) {
		this.operationid = operationid;
		this.actions = actions;
		this.operationtype = operationtype;
		this.escPeriod = escPeriod;
		this.escStepFrom = escStepFrom;
		this.escStepTo = escStepTo;
		this.evaltype = evaltype;
		this.opmessage = opmessage;
		this.opmessageGrps = opmessageGrps;
		this.opconditionses = opconditionses;
		this.opcommandHsts = opcommandHsts;
		this.opcommandGrps = opcommandGrps;
		this.opmessageUsrs = opmessageUsrs;
		this.opgroups = opgroups;
		this.optemplates = optemplates;
		this.opcommand = opcommand;
		this.opinventory = opinventory;
	}

	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	public int getOperationtype() {
		return this.operationtype;
	}

	public void setOperationtype(int operationtype) {
		this.operationtype = operationtype;
	}

	public int getEscPeriod() {
		return this.escPeriod;
	}

	public void setEscPeriod(int escPeriod) {
		this.escPeriod = escPeriod;
	}

	public int getEscStepFrom() {
		return this.escStepFrom;
	}

	public void setEscStepFrom(int escStepFrom) {
		this.escStepFrom = escStepFrom;
	}

	public int getEscStepTo() {
		return this.escStepTo;
	}

	public void setEscStepTo(int escStepTo) {
		this.escStepTo = escStepTo;
	}

	public int getEvaltype() {
		return this.evaltype;
	}

	public void setEvaltype(int evaltype) {
		this.evaltype = evaltype;
	}

	public Opmessage getOpmessage() {
		return this.opmessage;
	}

	public void setOpmessage(Opmessage opmessage) {
		this.opmessage = opmessage;
	}

	public Set getOpmessageGrps() {
		return this.opmessageGrps;
	}

	public void setOpmessageGrps(Set opmessageGrps) {
		this.opmessageGrps = opmessageGrps;
	}

	public Set getOpconditionses() {
		return this.opconditionses;
	}

	public void setOpconditionses(Set opconditionses) {
		this.opconditionses = opconditionses;
	}

	public Set getOpcommandHsts() {
		return this.opcommandHsts;
	}

	public void setOpcommandHsts(Set opcommandHsts) {
		this.opcommandHsts = opcommandHsts;
	}

	public Set getOpcommandGrps() {
		return this.opcommandGrps;
	}

	public void setOpcommandGrps(Set opcommandGrps) {
		this.opcommandGrps = opcommandGrps;
	}

	public Set getOpmessageUsrs() {
		return this.opmessageUsrs;
	}

	public void setOpmessageUsrs(Set opmessageUsrs) {
		this.opmessageUsrs = opmessageUsrs;
	}

	public Set getOpgroups() {
		return this.opgroups;
	}

	public void setOpgroups(Set opgroups) {
		this.opgroups = opgroups;
	}

	public Set getOptemplates() {
		return this.optemplates;
	}

	public void setOptemplates(Set optemplates) {
		this.optemplates = optemplates;
	}

	public Opcommand getOpcommand() {
		return this.opcommand;
	}

	public void setOpcommand(Opcommand opcommand) {
		this.opcommand = opcommand;
	}

	public Opinventory getOpinventory() {
		return this.opinventory;
	}

	public void setOpinventory(Opinventory opinventory) {
		this.opinventory = opinventory;
	}

}
