package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Opgroup generated by hbm2java
 */
public class Opgroup implements java.io.Serializable {

	private long opgroupid;
	private Operations operations;
	private Groups groups;

	public Opgroup() {
	}

	public Opgroup(long opgroupid, Operations operations, Groups groups) {
		this.opgroupid = opgroupid;
		this.operations = operations;
		this.groups = groups;
	}

	public long getOpgroupid() {
		return this.opgroupid;
	}

	public void setOpgroupid(long opgroupid) {
		this.opgroupid = opgroupid;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

}
