package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Opinventory generated by hbm2java
 */
public class Opinventory implements java.io.Serializable {

	private long operationid;
	private Operations operations;
	private int inventoryMode;

	public Opinventory() {
	}

	public Opinventory(Operations operations, int inventoryMode) {
		this.operations = operations;
		this.inventoryMode = inventoryMode;
	}

	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	public int getInventoryMode() {
		return this.inventoryMode;
	}

	public void setInventoryMode(int inventoryMode) {
		this.inventoryMode = inventoryMode;
	}

}
