package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Opmessage generated by hbm2java
 */
public class Opmessage implements java.io.Serializable {

	private long operationid;
	private Operations operations;
	private MediaType mediaType;
	private int defaultMsg;
	private String subject;
	private String message;

	public Opmessage() {
	}

	public Opmessage(Operations operations, int defaultMsg, String subject,
			String message) {
		this.operations = operations;
		this.defaultMsg = defaultMsg;
		this.subject = subject;
		this.message = message;
	}

	public Opmessage(Operations operations, MediaType mediaType,
			int defaultMsg, String subject, String message) {
		this.operations = operations;
		this.mediaType = mediaType;
		this.defaultMsg = defaultMsg;
		this.subject = subject;
		this.message = message;
	}

	public long getOperationid() {
		return this.operationid;
	}

	public void setOperationid(long operationid) {
		this.operationid = operationid;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	public MediaType getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(MediaType mediaType) {
		this.mediaType = mediaType;
	}

	public int getDefaultMsg() {
		return this.defaultMsg;
	}

	public void setDefaultMsg(int defaultMsg) {
		this.defaultMsg = defaultMsg;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
