package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * OpmessageGrp generated by hbm2java
 */
public class OpmessageGrp implements java.io.Serializable {

	private long opmessageGrpid;
	private Operations operations;
	private Usrgrp usrgrp;

	public OpmessageGrp() {
	}

	public OpmessageGrp(long opmessageGrpid, Operations operations,
			Usrgrp usrgrp) {
		this.opmessageGrpid = opmessageGrpid;
		this.operations = operations;
		this.usrgrp = usrgrp;
	}

	public long getOpmessageGrpid() {
		return this.opmessageGrpid;
	}

	public void setOpmessageGrpid(long opmessageGrpid) {
		this.opmessageGrpid = opmessageGrpid;
	}

	public Operations getOperations() {
		return this.operations;
	}

	public void setOperations(Operations operations) {
		this.operations = operations;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

}
