package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ProxyDhistory generated by hbm2java
 */
public class ProxyDhistory implements java.io.Serializable {

	private Long id;
	private int clock;
	private long druleid;
	private int type;
	private String ip;
	private int port;
	private String key;
	private String value;
	private int status;
	private Long dcheckid;
	private String dns;

	public ProxyDhistory() {
	}

	public ProxyDhistory(int clock, long druleid, int type, String ip,
			int port, String key, String value, int status, String dns) {
		this.clock = clock;
		this.druleid = druleid;
		this.type = type;
		this.ip = ip;
		this.port = port;
		this.key = key;
		this.value = value;
		this.status = status;
		this.dns = dns;
	}

	public ProxyDhistory(int clock, long druleid, int type, String ip,
			int port, String key, String value, int status, Long dcheckid,
			String dns) {
		this.clock = clock;
		this.druleid = druleid;
		this.type = type;
		this.ip = ip;
		this.port = port;
		this.key = key;
		this.value = value;
		this.status = status;
		this.dcheckid = dcheckid;
		this.dns = dns;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public long getDruleid() {
		return this.druleid;
	}

	public void setDruleid(long druleid) {
		this.druleid = druleid;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getDcheckid() {
		return this.dcheckid;
	}

	public void setDcheckid(Long dcheckid) {
		this.dcheckid = dcheckid;
	}

	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

}
