package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ProxyHistory generated by hbm2java
 */
public class ProxyHistory implements java.io.Serializable {

	private Long id;
	private int timestamp;
	private long itemid;
	private int clock;
	private String source;
	private int severity;
	private String value;
	private int logeventid;
	private int ns;
	private int state;
	private long lastlogsize;
	private int mtime;
	private int flags;

	public ProxyHistory() {
	}

	public ProxyHistory(long itemid, int clock, String source, int severity,
			String value, int logeventid, int ns, int state, long lastlogsize,
			int mtime, int flags) {
		this.itemid = itemid;
		this.clock = clock;
		this.source = source;
		this.severity = severity;
		this.value = value;
		this.logeventid = logeventid;
		this.ns = ns;
		this.state = state;
		this.lastlogsize = lastlogsize;
		this.mtime = mtime;
		this.flags = flags;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(int timestamp) {
		this.timestamp = timestamp;
	}

	public long getItemid() {
		return this.itemid;
	}

	public void setItemid(long itemid) {
		this.itemid = itemid;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public int getSeverity() {
		return this.severity;
	}

	public void setSeverity(int severity) {
		this.severity = severity;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getLogeventid() {
		return this.logeventid;
	}

	public void setLogeventid(int logeventid) {
		this.logeventid = logeventid;
	}

	public int getNs() {
		return this.ns;
	}

	public void setNs(int ns) {
		this.ns = ns;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public long getLastlogsize() {
		return this.lastlogsize;
	}

	public void setLastlogsize(long lastlogsize) {
		this.lastlogsize = lastlogsize;
	}

	public int getMtime() {
		return this.mtime;
	}

	public void setMtime(int mtime) {
		this.mtime = mtime;
	}

	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
