package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Regexps generated by hbm2java
 */
public class Regexps implements java.io.Serializable {

	private long regexpid;
	private String name;
	private String testString;
	private Set expressionses = new HashSet(0);

	public Regexps() {
	}

	public Regexps(long regexpid, String name, String testString) {
		this.regexpid = regexpid;
		this.name = name;
		this.testString = testString;
	}

	public Regexps(long regexpid, String name, String testString,
			Set expressionses) {
		this.regexpid = regexpid;
		this.name = name;
		this.testString = testString;
		this.expressionses = expressionses;
	}

	public long getRegexpid() {
		return this.regexpid;
	}

	public void setRegexpid(long regexpid) {
		this.regexpid = regexpid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTestString() {
		return this.testString;
	}

	public void setTestString(String testString) {
		this.testString = testString;
	}

	public Set getExpressionses() {
		return this.expressionses;
	}

	public void setExpressionses(Set expressionses) {
		this.expressionses = expressionses;
	}

}
