package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Rights generated by hbm2java
 */
public class Rights implements java.io.Serializable {

	private long rightid;
	private Usrgrp usrgrp;
	private Groups groups;
	private int permission;

	public Rights() {
	}

	public Rights(long rightid, Usrgrp usrgrp, Groups groups, int permission) {
		this.rightid = rightid;
		this.usrgrp = usrgrp;
		this.groups = groups;
		this.permission = permission;
	}

	public long getRightid() {
		return this.rightid;
	}

	public void setRightid(long rightid) {
		this.rightid = rightid;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

}
