package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ScreenUsrgrp generated by hbm2java
 */
public class ScreenUsrgrp implements java.io.Serializable {

	private long screenusrgrpid;
	private Screens screens;
	private Usrgrp usrgrp;
	private int permission;

	public ScreenUsrgrp() {
	}

	public ScreenUsrgrp(long screenusrgrpid, Screens screens, Usrgrp usrgrp,
			int permission) {
		this.screenusrgrpid = screenusrgrpid;
		this.screens = screens;
		this.usrgrp = usrgrp;
		this.permission = permission;
	}

	public long getScreenusrgrpid() {
		return this.screenusrgrpid;
	}

	public void setScreenusrgrpid(long screenusrgrpid) {
		this.screenusrgrpid = screenusrgrpid;
	}

	public Screens getScreens() {
		return this.screens;
	}

	public void setScreens(Screens screens) {
		this.screens = screens;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

}
