package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Scripts generated by hbm2java
 */
public class Scripts implements java.io.Serializable {

	private long scriptid;
	private Groups groups;
	private Usrgrp usrgrp;
	private String name;
	private String command;
	private int hostAccess;
	private String description;
	private String confirmation;
	private int type;
	private int executeOn;
	private Set opcommands = new HashSet(0);

	public Scripts() {
	}

	public Scripts(long scriptid, String name, String command, int hostAccess,
			String description, String confirmation, int type, int executeOn) {
		this.scriptid = scriptid;
		this.name = name;
		this.command = command;
		this.hostAccess = hostAccess;
		this.description = description;
		this.confirmation = confirmation;
		this.type = type;
		this.executeOn = executeOn;
	}

	public Scripts(long scriptid, Groups groups, Usrgrp usrgrp, String name,
			String command, int hostAccess, String description,
			String confirmation, int type, int executeOn, Set opcommands) {
		this.scriptid = scriptid;
		this.groups = groups;
		this.usrgrp = usrgrp;
		this.name = name;
		this.command = command;
		this.hostAccess = hostAccess;
		this.description = description;
		this.confirmation = confirmation;
		this.type = type;
		this.executeOn = executeOn;
		this.opcommands = opcommands;
	}

	public long getScriptid() {
		return this.scriptid;
	}

	public void setScriptid(long scriptid) {
		this.scriptid = scriptid;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	public int getHostAccess() {
		return this.hostAccess;
	}

	public void setHostAccess(int hostAccess) {
		this.hostAccess = hostAccess;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getConfirmation() {
		return this.confirmation;
	}

	public void setConfirmation(String confirmation) {
		this.confirmation = confirmation;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getExecuteOn() {
		return this.executeOn;
	}

	public void setExecuteOn(int executeOn) {
		this.executeOn = executeOn;
	}

	public Set getOpcommands() {
		return this.opcommands;
	}

	public void setOpcommands(Set opcommands) {
		this.opcommands = opcommands;
	}

}
