package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ServicesTimes generated by hbm2java
 */
public class ServicesTimes implements java.io.Serializable {

	private long timeid;
	private Services services;
	private int type;
	private int tsFrom;
	private int tsTo;
	private String note;

	public ServicesTimes() {
	}

	public ServicesTimes(long timeid, Services services, int type, int tsFrom,
			int tsTo, String note) {
		this.timeid = timeid;
		this.services = services;
		this.type = type;
		this.tsFrom = tsFrom;
		this.tsTo = tsTo;
		this.note = note;
	}

	public long getTimeid() {
		return this.timeid;
	}

	public void setTimeid(long timeid) {
		this.timeid = timeid;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getTsFrom() {
		return this.tsFrom;
	}

	public void setTsFrom(int tsFrom) {
		this.tsFrom = tsFrom;
	}

	public int getTsTo() {
		return this.tsTo;
	}

	public void setTsTo(int tsTo) {
		this.tsTo = tsTo;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
