package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ServiceAlarms generated by hbm2java
 */
public class ServiceAlarms implements java.io.Serializable {

	private long servicealarmid;
	private Services services;
	private int clock;
	private int value;

	public ServiceAlarms() {
	}

	public ServiceAlarms(long servicealarmid, Services services, int clock,
			int value) {
		this.servicealarmid = servicealarmid;
		this.services = services;
		this.clock = clock;
		this.value = value;
	}

	public long getServicealarmid() {
		return this.servicealarmid;
	}

	public void setServicealarmid(long servicealarmid) {
		this.servicealarmid = servicealarmid;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public int getClock() {
		return this.clock;
	}

	public void setClock(int clock) {
		this.clock = clock;
	}

	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

}
