package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * ServicesLinks generated by hbm2java
 */
public class ServicesLinks implements java.io.Serializable {

	private long linkid;
	private Services servicesByServiceupid;
	private Services servicesByServicedownid;
	private int soft;

	public ServicesLinks() {
	}

	public ServicesLinks(long linkid, Services servicesByServiceupid,
			Services servicesByServicedownid, int soft) {
		this.linkid = linkid;
		this.servicesByServiceupid = servicesByServiceupid;
		this.servicesByServicedownid = servicesByServicedownid;
		this.soft = soft;
	}

	public long getLinkid() {
		return this.linkid;
	}

	public void setLinkid(long linkid) {
		this.linkid = linkid;
	}

	public Services getServicesByServiceupid() {
		return this.servicesByServiceupid;
	}

	public void setServicesByServiceupid(Services servicesByServiceupid) {
		this.servicesByServiceupid = servicesByServiceupid;
	}

	public Services getServicesByServicedownid() {
		return this.servicesByServicedownid;
	}

	public void setServicesByServicedownid(Services servicesByServicedownid) {
		this.servicesByServicedownid = servicesByServicedownid;
	}

	public int getSoft() {
		return this.soft;
	}

	public void setSoft(int soft) {
		this.soft = soft;
	}

}
