package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Sessions generated by hbm2java
 */
public class Sessions implements java.io.Serializable {

	private String sessionid;
	private Users users;
	private int lastaccess;
	private int status;

	public Sessions() {
	}

	public Sessions(String sessionid, Users users, int lastaccess, int status) {
		this.sessionid = sessionid;
		this.users = users;
		this.lastaccess = lastaccess;
		this.status = status;
	}

	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getLastaccess() {
		return this.lastaccess;
	}

	public void setLastaccess(int lastaccess) {
		this.lastaccess = lastaccess;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
