package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Slideshows generated by hbm2java
 */
public class Slideshows implements java.io.Serializable {

	private long slideshowid;
	private Users users;
	private String name;
	private int delay;
	private int private_;
	private Set slideses = new HashSet(0);
	private Set slideshowUsrgrps = new HashSet(0);
	private Set slideshowUsers = new HashSet(0);

	public Slideshows() {
	}

	public Slideshows(long slideshowid, Users users, String name, int delay,
			int private_) {
		this.slideshowid = slideshowid;
		this.users = users;
		this.name = name;
		this.delay = delay;
		this.private_ = private_;
	}

	public Slideshows(long slideshowid, Users users, String name, int delay,
			int private_, Set slideses, Set slideshowUsrgrps, Set slideshowUsers) {
		this.slideshowid = slideshowid;
		this.users = users;
		this.name = name;
		this.delay = delay;
		this.private_ = private_;
		this.slideses = slideses;
		this.slideshowUsrgrps = slideshowUsrgrps;
		this.slideshowUsers = slideshowUsers;
	}

	public long getSlideshowid() {
		return this.slideshowid;
	}

	public void setSlideshowid(long slideshowid) {
		this.slideshowid = slideshowid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

	public int getPrivate_() {
		return this.private_;
	}

	public void setPrivate_(int private_) {
		this.private_ = private_;
	}

	public Set getSlideses() {
		return this.slideses;
	}

	public void setSlideses(Set slideses) {
		this.slideses = slideses;
	}

	public Set getSlideshowUsrgrps() {
		return this.slideshowUsrgrps;
	}

	public void setSlideshowUsrgrps(Set slideshowUsrgrps) {
		this.slideshowUsrgrps = slideshowUsrgrps;
	}

	public Set getSlideshowUsers() {
		return this.slideshowUsers;
	}

	public void setSlideshowUsers(Set slideshowUsers) {
		this.slideshowUsers = slideshowUsers;
	}

}
