package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * Slides generated by hbm2java
 */
public class Slides implements java.io.Serializable {

	private long slideid;
	private Screens screens;
	private Slideshows slideshows;
	private int step;
	private int delay;

	public Slides() {
	}

	public Slides(long slideid, Screens screens, Slideshows slideshows,
			int step, int delay) {
		this.slideid = slideid;
		this.screens = screens;
		this.slideshows = slideshows;
		this.step = step;
		this.delay = delay;
	}

	public long getSlideid() {
		return this.slideid;
	}

	public void setSlideid(long slideid) {
		this.slideid = slideid;
	}

	public Screens getScreens() {
		return this.screens;
	}

	public void setScreens(Screens screens) {
		this.screens = screens;
	}

	public Slideshows getSlideshows() {
		return this.slideshows;
	}

	public void setSlideshows(Slideshows slideshows) {
		this.slideshows = slideshows;
	}

	public int getStep() {
		return this.step;
	}

	public void setStep(int step) {
		this.step = step;
	}

	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

}
