package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysmapsLinks generated by hbm2java
 */
public class SysmapsLinks implements java.io.Serializable {

	private long linkid;
	private SysmapsElements sysmapsElementsBySelementid2;
	private Sysmaps sysmaps;
	private SysmapsElements sysmapsElementsBySelementid1;
	private int drawtype;
	private String color;
	private String label;
	private Set sysmapsLinkTriggerses = new HashSet(0);

	public SysmapsLinks() {
	}

	public SysmapsLinks(long linkid,
			SysmapsElements sysmapsElementsBySelementid2, Sysmaps sysmaps,
			SysmapsElements sysmapsElementsBySelementid1, int drawtype,
			String color, String label) {
		this.linkid = linkid;
		this.sysmapsElementsBySelementid2 = sysmapsElementsBySelementid2;
		this.sysmaps = sysmaps;
		this.sysmapsElementsBySelementid1 = sysmapsElementsBySelementid1;
		this.drawtype = drawtype;
		this.color = color;
		this.label = label;
	}

	public SysmapsLinks(long linkid,
			SysmapsElements sysmapsElementsBySelementid2, Sysmaps sysmaps,
			SysmapsElements sysmapsElementsBySelementid1, int drawtype,
			String color, String label, Set sysmapsLinkTriggerses) {
		this.linkid = linkid;
		this.sysmapsElementsBySelementid2 = sysmapsElementsBySelementid2;
		this.sysmaps = sysmaps;
		this.sysmapsElementsBySelementid1 = sysmapsElementsBySelementid1;
		this.drawtype = drawtype;
		this.color = color;
		this.label = label;
		this.sysmapsLinkTriggerses = sysmapsLinkTriggerses;
	}

	public long getLinkid() {
		return this.linkid;
	}

	public void setLinkid(long linkid) {
		this.linkid = linkid;
	}

	public SysmapsElements getSysmapsElementsBySelementid2() {
		return this.sysmapsElementsBySelementid2;
	}

	public void setSysmapsElementsBySelementid2(
			SysmapsElements sysmapsElementsBySelementid2) {
		this.sysmapsElementsBySelementid2 = sysmapsElementsBySelementid2;
	}

	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	public SysmapsElements getSysmapsElementsBySelementid1() {
		return this.sysmapsElementsBySelementid1;
	}

	public void setSysmapsElementsBySelementid1(
			SysmapsElements sysmapsElementsBySelementid1) {
		this.sysmapsElementsBySelementid1 = sysmapsElementsBySelementid1;
	}

	public int getDrawtype() {
		return this.drawtype;
	}

	public void setDrawtype(int drawtype) {
		this.drawtype = drawtype;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set getSysmapsLinkTriggerses() {
		return this.sysmapsLinkTriggerses;
	}

	public void setSysmapsLinkTriggerses(Set sysmapsLinkTriggerses) {
		this.sysmapsLinkTriggerses = sysmapsLinkTriggerses;
	}

}
