package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * SysmapUser generated by hbm2java
 */
public class SysmapUser implements java.io.Serializable {

	private long sysmapuserid;
	private Sysmaps sysmaps;
	private Users users;
	private int permission;

	public SysmapUser() {
	}

	public SysmapUser(long sysmapuserid, Sysmaps sysmaps, Users users,
			int permission) {
		this.sysmapuserid = sysmapuserid;
		this.sysmaps = sysmaps;
		this.users = users;
		this.permission = permission;
	}

	public long getSysmapuserid() {
		return this.sysmapuserid;
	}

	public void setSysmapuserid(long sysmapuserid) {
		this.sysmapuserid = sysmapuserid;
	}

	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

}
