package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * SysmapUsrgrp generated by hbm2java
 */
public class SysmapUsrgrp implements java.io.Serializable {

	private long sysmapusrgrpid;
	private Usrgrp usrgrp;
	private Sysmaps sysmaps;
	private int permission;

	public SysmapUsrgrp() {
	}

	public SysmapUsrgrp(long sysmapusrgrpid, Usrgrp usrgrp, Sysmaps sysmaps,
			int permission) {
		this.sysmapusrgrpid = sysmapusrgrpid;
		this.usrgrp = usrgrp;
		this.sysmaps = sysmaps;
		this.permission = permission;
	}

	public long getSysmapusrgrpid() {
		return this.sysmapusrgrpid;
	}

	public void setSysmapusrgrpid(long sysmapusrgrpid) {
		this.sysmapusrgrpid = sysmapusrgrpid;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

}
