package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * SysmapUrl generated by hbm2java
 */
public class SysmapUrl implements java.io.Serializable {

	private long sysmapurlid;
	private Sysmaps sysmaps;
	private String name;
	private String url;
	private int elementtype;

	public SysmapUrl() {
	}

	public SysmapUrl(long sysmapurlid, Sysmaps sysmaps, String name,
			String url, int elementtype) {
		this.sysmapurlid = sysmapurlid;
		this.sysmaps = sysmaps;
		this.name = name;
		this.url = url;
		this.elementtype = elementtype;
	}

	public long getSysmapurlid() {
		return this.sysmapurlid;
	}

	public void setSysmapurlid(long sysmapurlid) {
		this.sysmapurlid = sysmapurlid;
	}

	public Sysmaps getSysmaps() {
		return this.sysmaps;
	}

	public void setSysmaps(Sysmaps sysmaps) {
		this.sysmaps = sysmaps;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getElementtype() {
		return this.elementtype;
	}

	public void setElementtype(int elementtype) {
		this.elementtype = elementtype;
	}

}
