package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * SysmapsLinkTriggers generated by hbm2java
 */
public class SysmapsLinkTriggers implements java.io.Serializable {

	private long linktriggerid;
	private SysmapsLinks sysmapsLinks;
	private Triggers triggers;
	private int drawtype;
	private String color;

	public SysmapsLinkTriggers() {
	}

	public SysmapsLinkTriggers(long linktriggerid, SysmapsLinks sysmapsLinks,
			Triggers triggers, int drawtype, String color) {
		this.linktriggerid = linktriggerid;
		this.sysmapsLinks = sysmapsLinks;
		this.triggers = triggers;
		this.drawtype = drawtype;
		this.color = color;
	}

	public long getLinktriggerid() {
		return this.linktriggerid;
	}

	public void setLinktriggerid(long linktriggerid) {
		this.linktriggerid = linktriggerid;
	}

	public SysmapsLinks getSysmapsLinks() {
		return this.sysmapsLinks;
	}

	public void setSysmapsLinks(SysmapsLinks sysmapsLinks) {
		this.sysmapsLinks = sysmapsLinks;
	}

	public Triggers getTriggers() {
		return this.triggers;
	}

	public void setTriggers(Triggers triggers) {
		this.triggers = triggers;
	}

	public int getDrawtype() {
		return this.drawtype;
	}

	public void setDrawtype(int drawtype) {
		this.drawtype = drawtype;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
