package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * SysmapElementUrl generated by hbm2java
 */
public class SysmapElementUrl implements java.io.Serializable {

	private long sysmapelementurlid;
	private SysmapsElements sysmapsElements;
	private String name;
	private String url;

	public SysmapElementUrl() {
	}

	public SysmapElementUrl(long sysmapelementurlid,
			SysmapsElements sysmapsElements, String name, String url) {
		this.sysmapelementurlid = sysmapelementurlid;
		this.sysmapsElements = sysmapsElements;
		this.name = name;
		this.url = url;
	}

	public long getSysmapelementurlid() {
		return this.sysmapelementurlid;
	}

	public void setSysmapelementurlid(long sysmapelementurlid) {
		this.sysmapelementurlid = sysmapelementurlid;
	}

	public SysmapsElements getSysmapsElements() {
		return this.sysmapsElements;
	}

	public void setSysmapsElements(SysmapsElements sysmapsElements) {
		this.sysmapsElements = sysmapsElements;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
