package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Timeperiods generated by hbm2java
 */
public class Timeperiods implements java.io.Serializable {

	private long timeperiodid;
	private int timeperiodType;
	private int every;
	private int month;
	private int dayofweek;
	private int day;
	private int startTime;
	private int period;
	private int startDate;
	private Set maintenancesWindowses = new HashSet(0);

	public Timeperiods() {
	}

	public Timeperiods(long timeperiodid, int timeperiodType, int every,
			int month, int dayofweek, int day, int startTime, int period,
			int startDate) {
		this.timeperiodid = timeperiodid;
		this.timeperiodType = timeperiodType;
		this.every = every;
		this.month = month;
		this.dayofweek = dayofweek;
		this.day = day;
		this.startTime = startTime;
		this.period = period;
		this.startDate = startDate;
	}

	public Timeperiods(long timeperiodid, int timeperiodType, int every,
			int month, int dayofweek, int day, int startTime, int period,
			int startDate, Set maintenancesWindowses) {
		this.timeperiodid = timeperiodid;
		this.timeperiodType = timeperiodType;
		this.every = every;
		this.month = month;
		this.dayofweek = dayofweek;
		this.day = day;
		this.startTime = startTime;
		this.period = period;
		this.startDate = startDate;
		this.maintenancesWindowses = maintenancesWindowses;
	}

	public long getTimeperiodid() {
		return this.timeperiodid;
	}

	public void setTimeperiodid(long timeperiodid) {
		this.timeperiodid = timeperiodid;
	}

	public int getTimeperiodType() {
		return this.timeperiodType;
	}

	public void setTimeperiodType(int timeperiodType) {
		this.timeperiodType = timeperiodType;
	}

	public int getEvery() {
		return this.every;
	}

	public void setEvery(int every) {
		this.every = every;
	}

	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	public int getDayofweek() {
		return this.dayofweek;
	}

	public void setDayofweek(int dayofweek) {
		this.dayofweek = dayofweek;
	}

	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	public int getStartTime() {
		return this.startTime;
	}

	public void setStartTime(int startTime) {
		this.startTime = startTime;
	}

	public int getPeriod() {
		return this.period;
	}

	public void setPeriod(int period) {
		this.period = period;
	}

	public int getStartDate() {
		return this.startDate;
	}

	public void setStartDate(int startDate) {
		this.startDate = startDate;
	}

	public Set getMaintenancesWindowses() {
		return this.maintenancesWindowses;
	}

	public void setMaintenancesWindowses(Set maintenancesWindowses) {
		this.maintenancesWindowses = maintenancesWindowses;
	}

}
