package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * TrendsUint generated by hbm2java
 */
public class TrendsUint implements java.io.Serializable {

	private TrendsUintId id;
	private int num;
	private long valueMin;
	private long valueAvg;
	private long valueMax;

	public TrendsUint() {
	}

	public TrendsUint(TrendsUintId id, int num, long valueMin, long valueAvg,
			long valueMax) {
		this.id = id;
		this.num = num;
		this.valueMin = valueMin;
		this.valueAvg = valueAvg;
		this.valueMax = valueMax;
	}

	public TrendsUintId getId() {
		return this.id;
	}

	public void setId(TrendsUintId id) {
		this.id = id;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public long getValueMin() {
		return this.valueMin;
	}

	public void setValueMin(long valueMin) {
		this.valueMin = valueMin;
	}

	public long getValueAvg() {
		return this.valueAvg;
	}

	public void setValueAvg(long valueAvg) {
		this.valueAvg = valueAvg;
	}

	public long getValueMax() {
		return this.valueMax;
	}

	public void setValueMax(long valueMax) {
		this.valueMax = valueMax;
	}

}
