package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * TriggerDiscovery generated by hbm2java
 */
public class TriggerDiscovery implements java.io.Serializable {

	private long triggerid;
	private Triggers triggersByParentTriggerid;
	private Triggers triggersByTriggerid;

	public TriggerDiscovery() {
	}

	public TriggerDiscovery(Triggers triggersByParentTriggerid,
			Triggers triggersByTriggerid) {
		this.triggersByParentTriggerid = triggersByParentTriggerid;
		this.triggersByTriggerid = triggersByTriggerid;
	}

	public long getTriggerid() {
		return this.triggerid;
	}

	public void setTriggerid(long triggerid) {
		this.triggerid = triggerid;
	}

	public Triggers getTriggersByParentTriggerid() {
		return this.triggersByParentTriggerid;
	}

	public void setTriggersByParentTriggerid(Triggers triggersByParentTriggerid) {
		this.triggersByParentTriggerid = triggersByParentTriggerid;
	}

	public Triggers getTriggersByTriggerid() {
		return this.triggersByTriggerid;
	}

	public void setTriggersByTriggerid(Triggers triggersByTriggerid) {
		this.triggersByTriggerid = triggersByTriggerid;
	}

}
