package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * TriggerDepends generated by hbm2java
 */
public class TriggerDepends implements java.io.Serializable {

	private long triggerdepid;
	private Triggers triggersByTriggeridDown;
	private Triggers triggersByTriggeridUp;

	public TriggerDepends() {
	}

	public TriggerDepends(long triggerdepid, Triggers triggersByTriggeridDown,
			Triggers triggersByTriggeridUp) {
		this.triggerdepid = triggerdepid;
		this.triggersByTriggeridDown = triggersByTriggeridDown;
		this.triggersByTriggeridUp = triggersByTriggeridUp;
	}

	public long getTriggerdepid() {
		return this.triggerdepid;
	}

	public void setTriggerdepid(long triggerdepid) {
		this.triggerdepid = triggerdepid;
	}

	public Triggers getTriggersByTriggeridDown() {
		return this.triggersByTriggeridDown;
	}

	public void setTriggersByTriggeridDown(Triggers triggersByTriggeridDown) {
		this.triggersByTriggeridDown = triggersByTriggeridDown;
	}

	public Triggers getTriggersByTriggeridUp() {
		return this.triggersByTriggeridUp;
	}

	public void setTriggersByTriggeridUp(Triggers triggersByTriggeridUp) {
		this.triggersByTriggeridUp = triggersByTriggeridUp;
	}

}
