package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

/**
 * UsersGroups generated by hbm2java
 */
public class UsersGroups implements java.io.Serializable {

	private long id;
	private Usrgrp usrgrp;
	private Users users;

	public UsersGroups() {
	}

	public UsersGroups(long id, Usrgrp usrgrp, Users users) {
		this.id = id;
		this.usrgrp = usrgrp;
		this.users = users;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usrgrp getUsrgrp() {
		return this.usrgrp;
	}

	public void setUsrgrp(Usrgrp usrgrp) {
		this.usrgrp = usrgrp;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
