package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private long userid;
	private String alias;
	private String name;
	private String surname;
	private String passwd;
	private String url;
	private int autologin;
	private int autologout;
	private String lang;
	private int refresh;
	private int type;
	private String theme;
	private int attemptFailed;
	private String attemptIp;
	private int attemptClock;
	private int rowsPerPage;
	private Set profileses = new HashSet(0);
	private Set slideshowses = new HashSet(0);
	private Set medias = new HashSet(0);
	private Set opmessageUsrs = new HashSet(0);
	private Set slideshowUsers = new HashSet(0);
	private Set sysmapses = new HashSet(0);
	private Set acknowledgeses = new HashSet(0);
	private Set auditlogs = new HashSet(0);
	private Set screenUsers = new HashSet(0);
	private Set alertses = new HashSet(0);
	private Set sessionses = new HashSet(0);
	private Set usersGroupses = new HashSet(0);
	private Set screenses = new HashSet(0);
	private Set sysmapUsers = new HashSet(0);

	public Users() {
	}

	public Users(long userid, String alias, String name, String surname,
			String passwd, String url, int autologin, int autologout,
			String lang, int refresh, int type, String theme,
			int attemptFailed, String attemptIp, int attemptClock,
			int rowsPerPage) {
		this.userid = userid;
		this.alias = alias;
		this.name = name;
		this.surname = surname;
		this.passwd = passwd;
		this.url = url;
		this.autologin = autologin;
		this.autologout = autologout;
		this.lang = lang;
		this.refresh = refresh;
		this.type = type;
		this.theme = theme;
		this.attemptFailed = attemptFailed;
		this.attemptIp = attemptIp;
		this.attemptClock = attemptClock;
		this.rowsPerPage = rowsPerPage;
	}

	public Users(long userid, String alias, String name, String surname,
			String passwd, String url, int autologin, int autologout,
			String lang, int refresh, int type, String theme,
			int attemptFailed, String attemptIp, int attemptClock,
			int rowsPerPage, Set profileses, Set slideshowses, Set medias,
			Set opmessageUsrs, Set slideshowUsers, Set sysmapses,
			Set acknowledgeses, Set auditlogs, Set screenUsers, Set alertses,
			Set sessionses, Set usersGroupses, Set screenses, Set sysmapUsers) {
		this.userid = userid;
		this.alias = alias;
		this.name = name;
		this.surname = surname;
		this.passwd = passwd;
		this.url = url;
		this.autologin = autologin;
		this.autologout = autologout;
		this.lang = lang;
		this.refresh = refresh;
		this.type = type;
		this.theme = theme;
		this.attemptFailed = attemptFailed;
		this.attemptIp = attemptIp;
		this.attemptClock = attemptClock;
		this.rowsPerPage = rowsPerPage;
		this.profileses = profileses;
		this.slideshowses = slideshowses;
		this.medias = medias;
		this.opmessageUsrs = opmessageUsrs;
		this.slideshowUsers = slideshowUsers;
		this.sysmapses = sysmapses;
		this.acknowledgeses = acknowledgeses;
		this.auditlogs = auditlogs;
		this.screenUsers = screenUsers;
		this.alertses = alertses;
		this.sessionses = sessionses;
		this.usersGroupses = usersGroupses;
		this.screenses = screenses;
		this.sysmapUsers = sysmapUsers;
	}

	public long getUserid() {
		return this.userid;
	}

	public void setUserid(long userid) {
		this.userid = userid;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getAutologin() {
		return this.autologin;
	}

	public void setAutologin(int autologin) {
		this.autologin = autologin;
	}

	public int getAutologout() {
		return this.autologout;
	}

	public void setAutologout(int autologout) {
		this.autologout = autologout;
	}

	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public int getRefresh() {
		return this.refresh;
	}

	public void setRefresh(int refresh) {
		this.refresh = refresh;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public int getAttemptFailed() {
		return this.attemptFailed;
	}

	public void setAttemptFailed(int attemptFailed) {
		this.attemptFailed = attemptFailed;
	}

	public String getAttemptIp() {
		return this.attemptIp;
	}

	public void setAttemptIp(String attemptIp) {
		this.attemptIp = attemptIp;
	}

	public int getAttemptClock() {
		return this.attemptClock;
	}

	public void setAttemptClock(int attemptClock) {
		this.attemptClock = attemptClock;
	}

	public int getRowsPerPage() {
		return this.rowsPerPage;
	}

	public void setRowsPerPage(int rowsPerPage) {
		this.rowsPerPage = rowsPerPage;
	}

	public Set getProfileses() {
		return this.profileses;
	}

	public void setProfileses(Set profileses) {
		this.profileses = profileses;
	}

	public Set getSlideshowses() {
		return this.slideshowses;
	}

	public void setSlideshowses(Set slideshowses) {
		this.slideshowses = slideshowses;
	}

	public Set getMedias() {
		return this.medias;
	}

	public void setMedias(Set medias) {
		this.medias = medias;
	}

	public Set getOpmessageUsrs() {
		return this.opmessageUsrs;
	}

	public void setOpmessageUsrs(Set opmessageUsrs) {
		this.opmessageUsrs = opmessageUsrs;
	}

	public Set getSlideshowUsers() {
		return this.slideshowUsers;
	}

	public void setSlideshowUsers(Set slideshowUsers) {
		this.slideshowUsers = slideshowUsers;
	}

	public Set getSysmapses() {
		return this.sysmapses;
	}

	public void setSysmapses(Set sysmapses) {
		this.sysmapses = sysmapses;
	}

	public Set getAcknowledgeses() {
		return this.acknowledgeses;
	}

	public void setAcknowledgeses(Set acknowledgeses) {
		this.acknowledgeses = acknowledgeses;
	}

	public Set getAuditlogs() {
		return this.auditlogs;
	}

	public void setAuditlogs(Set auditlogs) {
		this.auditlogs = auditlogs;
	}

	public Set getScreenUsers() {
		return this.screenUsers;
	}

	public void setScreenUsers(Set screenUsers) {
		this.screenUsers = screenUsers;
	}

	public Set getAlertses() {
		return this.alertses;
	}

	public void setAlertses(Set alertses) {
		this.alertses = alertses;
	}

	public Set getSessionses() {
		return this.sessionses;
	}

	public void setSessionses(Set sessionses) {
		this.sessionses = sessionses;
	}

	public Set getUsersGroupses() {
		return this.usersGroupses;
	}

	public void setUsersGroupses(Set usersGroupses) {
		this.usersGroupses = usersGroupses;
	}

	public Set getScreenses() {
		return this.screenses;
	}

	public void setScreenses(Set screenses) {
		this.screenses = screenses;
	}

	public Set getSysmapUsers() {
		return this.sysmapUsers;
	}

	public void setSysmapUsers(Set sysmapUsers) {
		this.sysmapUsers = sysmapUsers;
	}

}
