package cn.com.esrichina.ServerMonitor.domain;

// Generated 2016-8-18 11:14:22 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Valuemaps generated by hbm2java
 */
public class Valuemaps implements java.io.Serializable {

	private long valuemapid;
	private String name;
	private Set itemses = new HashSet(0);
	private Set mappingses = new HashSet(0);

	public Valuemaps() {
	}

	public Valuemaps(long valuemapid, String name) {
		this.valuemapid = valuemapid;
		this.name = name;
	}

	public Valuemaps(long valuemapid, String name, Set itemses, Set mappingses) {
		this.valuemapid = valuemapid;
		this.name = name;
		this.itemses = itemses;
		this.mappingses = mappingses;
	}

	public long getValuemapid() {
		return this.valuemapid;
	}

	public void setValuemapid(long valuemapid) {
		this.valuemapid = valuemapid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItemses() {
		return this.itemses;
	}

	public void setItemses(Set itemses) {
		this.itemses = itemses;
	}

	public Set getMappingses() {
		return this.mappingses;
	}

	public void setMappingses(Set mappingses) {
		this.mappingses = mappingses;
	}

}
